### ISSUE TITLE
Build SPHinXsys in a different Linux distriburion

### ISSUE THREAD

**Issue by rubensamarojr** [Xiangyu-Hu/SPHinXsys#101]
Hi there,

Maybe it can help others to build (compile) SPHinXsys in different unix distributions. (I also don't rule out the possibility that I did something wrong :confused:)

I built SPHinXsys on CentOS 7. In my case, _Cmake, gcc, LAPACK_ and _BLAS_ were already installed in the root directory.

After downloading and installing the prerequisites below:
_Google test framework_
_BOOST library_
_TBB library_
_Simbody library_

I added to my **.bashrc file** the following commands:

export GTEST_ROOT=/path/to/gtest
export GTEST_HOME=/path/to/gtest
export LIBRARY_PATH=$GTEST_HOME/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=$LIBRARY_PATH:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH=$GTEST_HOME/include:$CPLUS_INCLUDE_PATH

export SIMBODY_HOME=/path/to/simbody
export LIBRARY_PATH=$SIMBODY_HOME/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=$LIBRARY_PATH:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH=$SIMBODY_HOME/include:$CPLUS_INCLUDE_PATH
export SIMBODY_LIB_DIR=$SIMBODY_HOME/lib64
export SIMBODY_INCLUDE_DIR=$SIMBODY_HOME/include
export SIMBODY_LIBRARIES=$SIMBODY_HOME/lib64
export SIMBODY_DEBUG_LIBRARIES=$SIMBODY_HOME/lib64
export SIMBODY_RELEASE_LIBRARIES=$SIMBODY_HOME/lib64

export TBB_HOME=/path/to/tbb
export TBB_INCLUDE_DIR=$TBB_HOME/include
export LIBRARY_PATH=$TBB_HOME/lib:$LIBRARY_PATH
export TBB_LIB_DIR=$TBB_HOME/lib
export TBB_LIB_DIR_TEMP=$TBB_HOME/lib
export LD_LIBRARY_PATH=$TBB_LIB_DIR:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH=$TBB_HOME/include:$CPLUS_INCLUDE_PATH
export TBB_LIBRARY_RELEASE=$TBB_HOME/lib
export TBB_LIBRARY_DEBUG=$TBB_HOME/lib

export BOOST_HOME=/path/to/boost-1.71.0

export EIGEN3_INCLUDE_DIR=/path/to/eigen-3.4.0
export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/path/to/eigen-3.4.0
export CPLUS_INCLUDE_PATH=$EIGEN3_INCLUDE_DIR:$CPLUS_INCLUDE_PATH

Then, after typing the comand **bash** in the terminal, it was possible to build and install SPHinXsys.

:warning: Some observations
- Certainly above there are more exports than necessary.
- I'm not sure, but maybe with minor changes on cmake files provided in SPHinXsys, cmake will find the libraries.
- In the step-by-step installation (https://www.sphinxsys.org/html/installation.html), I think that after the text "After installing Simbody correctly, set environment variable"
_echo 'export TBB_HOME=/path/to/tbb' >> ~/.bash_profile_ 
**should be** 
_echo 'export SIMBODY_HOME=/path/to/simbody' >> ~/.bash_profile_
**and**
_echo 'export TBB_HOME=/path/to/tbb' >> ~/.bashrc_
**should be**
_echo 'export SIMBODY_HOME=/path/to/simbody' >> ~/.bashrc_

**Comment by Xiangyu-Hu** [comment]
Hi, 
Thanks for pointing out the errors in installation instructions. The correction will be updated soon,

For the issues in a different Linux distribution, it is great that you have found a way to install with effort.
Could you also send the original error message, before you found a new way? 
So that we can  possibly fix the bug in Cmake file and avoid similar issue later?
Thanks.

**Comment by rubensamarojr** [comment]
Hi Prof. @Xiangyu-Hu ,

Following the instructions of [the dependency-free version](https://www.sphinxsys.org/html/installation.html#installing-on-ubunutu-linux-using-the-dependency-free-version) I got errors related to gtest path, e.g.:
fatal error: gtest/gtest.h: No such file or directory
error while loading shared libraries: libgtest.so.XX: cannot open shared object file: No such file or directory

Downloading and installing the libraries Eigen, TBB, and Simbody in a different directory, I got some errors related to Eigen include path and Simbody dynamic libraries path. Some errors like:
fatal error: Eigen/Eigenvalues: No such file or directory #  include <Eigen/Eigenvalues>

Best

**Comment by Xiangyu-Hu** [comment]
Hi,

Thanks. It seems that this instruction is out of date.
We update it as soon as possible.

For general propose, we suggest to use version with dependence.

Xiangyu
