### ISSUE TITLE
Wave paddle modeling in SPHinXsys

### ISSUE THREAD

**Issue by mohammadrezat** [Xiangyu-Hu/SPHinXsys#112]
Hi Everyone,
I've recently become familiar with your articles and SPHinXsys Program. I must admit that your code has impressive FSI simulation capabilities.
For my new research, I must simulate the interaction of regular waves with a single flexible structure. Multi-resolution FSI coupling benchmark test of SPHinXsys works exceptionally well and is highly applicable to my research endeavors.

However, I would like to know how to embed a wave paddle into your code. Does a predetermined method? Or perhaps you could assist me in implementing wave-paddle in SPHinXsys.

**Comment by Xiangyu-Hu** [comment]
@mohammadrezat hi, I think that you can post thes specific issue related with the code. Based on that, a discussion would be easier. Thanks. Xiangyu

**Comment by mohammadrezat** [comment]
Dear Prof. @Xiangyu-Hu , 
I found OWSC test case in SPhinxsys and i want to modify this case.
I want to replace elastic stem instead of OWSC system. Then determine deformation of this object induced by regular wave.
I appreciate that guide me on this matter.

**Comment by mohammadrezat** [comment]
@Xiangyu-Hu Many thanks for your support, I back soon with my modified code.
