### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by mohammadrezat** [Xiangyu-Hu/SPHinXsys#117]
Dear Prof. @Xiangyu-Hu,
I start to install SPHinXsys on windows, i completed installation steps by video in youtube but in the step that "configure SPHinXsys with cmake", i encountered with following error:

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (Simbody)
  does not match the name of the calling package (SIMBODY).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindSIMBODY.cmake:189 (find_package_handle_standard_args)
  cmake/Import3rdpartylibs.cmake:3 (FIND_PACKAGE)
  CMakeLists.txt:122 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

C:/Simbody/include
C:/Simbody/lib
SimTKsimbody;SimTKmath;SimTKcommon;liblapack;libblas;pthreadVC2_x64
SimTKsimbody;SimTKmath;SimTKcommon;liblapack;libblas;pthreadVC2_x64
liblapack;libblas;pthreadVC2_x64
C:/tbb2019_20191006oss/include
C:/tbb2019_20191006oss/lib/intel64/vc14
tbb;tbbmalloc;tbbmalloc_proxy
C:/boost_1_74_0
C:/boost_1_74_0/lib64-msvc-14.1
optimized;C:/boost_1_74_0/lib64-msvc-14.1/boost_program_options-vc141-mt-x64-1_74.lib;debug;C:/boost_1_74_0/lib64-msvc-14.1/boost_program_options-vc141-mt-gd-x64-1_74.lib
CMake Error at cmake/Import3rdpartylibs.cmake:55 (find_package):
  Could not find a package configuration file provided by "GTest" with any of
  the following names:

    GTestConfig.cmake
    gtest-config.cmake

  Add the installation prefix of "GTest" to CMAKE_PREFIX_PATH or set
  "GTest_DIR" to a directory containing one of the above files.  If "GTest"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:122 (include)

**Comment by Xiangyu-Hu** [comment]
#111 The google test should be installed first.
