### ISSUE TITLE
\\wsl$\Ubuntu-20.04\home\aas\tests\3d_examples\test_3d_particle_relaxation

### ISSUE THREAD

**Issue by AhmedSalih3d** [Xiangyu-Hu/SPHinXsys#118]
Is there any guide on how to:

- Compile and run this example from the .cpp file? I am not sure how to do it.

Thanks.

Kind regards

**Comment by Xiangyu-Hu** [comment]
you need first build the case. After cmake in the build folder. You can go to the sub folder tests\3d_examples\test_3d_particle_relaxation and run make and run ctest to execute the case. Or you go to /bin to run it directly with proper input arguments.

**Comment by AhmedSalih3d** [comment]
Hi, thanks for your answer. This is where I struggled since I was not able to change parameters in cpp file (i.e. use a different stl), recompile and then run the calculation.

Do you happen to have a much more detailed example going through it step by step? I am new to having to compile simulations before running them, this is why it is difficult for me.

Kind regards

**Comment by Xiangyu-Hu** [comment]
I think that you can simply change another stl file, the only things is that you need is setting the domain bounds so that the model is inside the domain. The domain information you can obtained from a STL viewer.

**Comment by AhmedSalih3d** [comment]
> I think that you can simply change another stl file, the only things is that you need is setting the domain bounds so that the model is inside the domain. The domain information you can obtained from a STL viewer.

Hi again!

That is of course true, but that is not what I want. I want to be able to play with particle spacing, relaxation parameters etc.

I cannot figure out how to do this. Please, do you have a step by step guide of how to:

- Take a cpp file
- Compile it in a way your program understands
- Execute the programme

So that I can use your nice tools in my workflow?

Kind regards

**Comment by Xiangyu-Hu** [comment]
I think that I may missed your point. As particle spacing is given in cpp or headers of the examples, 
you can simply change it and recompile the file and run it.
There is no explicit relaxation parameters, the only you can so is change the number iteration steps. But the difference of the results is minor if the number is sufficiently high.

For your workflow, I do not understand what you really mean. Is it something with your work?

If I am not wrong, I guess that we want write one your own code using the library and run it.
The simplest way you can do, add your folder into the main source folder at the same level as the test , and include such folder into the Cmakelists file, then you own work will also been built.
The other way is that you install the library and include the library to your code . 
Then you can also compile it with your own code.

**Comment by AhmedSalih3d** [comment]
Exactly! 

This is where I am stuck, in the sphinxsys-build directory I cannot find any cpp files! 

![image](https://user-images.githubusercontent.com/36305327/170759584-18c505fb-2978-483c-b78f-140b059b92ee.png)

It compiles completely fine, but I have no clue where to change anything in the cpp/header file?

With own work, I meant that I wanted to export the particle file based on relaxation to another software I use - this I can easily do, but I cannot yet use your library since I do not understand how to change a parameter in cpp and recompile.

Kind regards

**Comment by Xiangyu-Hu** [comment]
Hi, the source files are still in the source folder. 
The present Cmake separate the two. 
If you modify the source and make again, your change will take effect.
