### ISSUE TITLE
Error in test case running

### ISSUE THREAD

**Issue by mohammadrezat** [Xiangyu-Hu/SPHinXsys#120]
Dear @Xiangyu-Hu 
I hope everything well with you.

I install the SPHinxsys on windows and when i want run the test 2dam break test case, i encountered with two error. 
picture of errors attached.
please help me about this issue.

![Capture](https://user-images.githubusercontent.com/105660912/169699333-b10cf77e-f616-4984-ba79-c248b3585f15.PNG)

**Comment by mohammadrezat** [comment]
Dear Prof. @Xiangyu-Hu 
Actually, My lib folder is empty in the : E:\SPHinXsys\SPHinXsys-BUILD\SPHINXsys\lib

**Comment by Xiangyu-Hu** [comment]
#111 The same issue that you need initialize the eigen 3 submodule in the repository,
