### ISSUE TITLE
请问新的release何时发行

### ISSUE THREAD

**Issue by Zhangh-hit** [Xiangyu-Hu/SPHinXsys#122]
尊敬的开发者：
        您好，我比较关心现在的master里的几个新算例，请问新的release版本何时发行，或者我可不可以使用现在的master版本。

**Comment by ChiZhangatTUM** [comment]
> 尊敬的开发者：
> 您好，我比较关心现在的master里的几个新算例，请问新的release版本何时发行，或者我可不可以使用现在的master版本。

Hi， please comment in English next time for other users. 
The new release will be given if all important features are well validated. 
You are free to use the Master branch
