### ISSUE TITLE
Problems about fluid sound speed in fsi2

### ISSUE THREAD

**Issue by wy-kong** [Xiangyu-Hu/SPHinXsys#140]
In the case fsi2, the value of fluid sound speed can largely influence the behavior of flow behind the cylinder. When using cf=20*U_f in line 33, the displacements of the beam tip decrease to a small value.
This problem exists for all the released versions.

**Comment by Xiangyu-Hu** [comment]
This the issue of numerical dissipation. As larger sound speed leads to large dissipation and hence less oscillation magnitude at the same resolution. However, this value will still converges to correct value with increase resolution.
