### ISSUE TITLE
Class `SoftConstrainSolidBodyRegion` cannot be used more than once for the same body

### ISSUE THREAD

**Issue by FabienPean-Virtonomy** [Xiangyu-Hu/SPHinXsys#142]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/190d0ef53122fb33e0dfb229f56ab0b2980b059d/SPHINXsys/src/shared/particle_dynamics/solid_dynamics/constraint_dynamics.cpp#L255-L264

Registering the variable prevents using several of this type of constraint in a single simulation because it leads to error if it is constructed more than once for the same body:
> Error: the variable 'TemporaryVelocity' has already been registered!

**Comment by Xiangyu-Hu** [comment]
Could you setup a new test case for this issue so that we can solve it by introduce new function in  BaseParticles ?

**Comment by FabienPean-Virtonomy** [comment]
I have other tasks at the moment. I think this problem should be solved by not relying on registering variable

**Comment by Xiangyu-Hu** [comment]
By using the shared data. It is not an issue now.
