### ISSUE TITLE
Installation error C2244

### ISSUE THREAD

**Issue by QiYuanyang** [Xiangyu-Hu/SPHinXsys#148]
I have been trying to install SPHinXsys following the instructions on the website and a video tutorial from bilibili. 
When building the sphinxsys, the sphinsys_2d and 3d lib files are not created. This is caused by C2244 errors in sphinxsys_2d.
I am using vs2017, the errors are as follows:

2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(107): error C2244: “SPH::MeshWithDataPackages<MeshFieldType,DataPackageType>::DataValueFromGlobalIndex”: 无法将函数定义与现有的声明匹配 (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(106): note: 参见“SPH::MeshWithDataPackages<MeshFieldType,DataPackageType>::DataValueFromGlobalIndex”的声明 (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(107): note: 定义 (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(107): note: 'DataType SPH::MeshWithDataPackages<MeshFieldType,DataPackageType>::DataValueFromGlobalIndex(const SPH::Vecu &)' (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(107): note: 现有声明 (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(107): note: 'DataType SPH::MeshWithDataPackages<MeshFieldType,DataPackageType>::DataValueFromGlobalIndex(const SPH::Vecu &)' (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(172): error C2244: “SPH::MeshWithDataPackages<MeshFieldType,DataPackageType>::probeMesh”: 无法将函数定义与现有的声明匹配 (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(171): note: 参见“SPH::MeshWithDataPackages<MeshFieldType,DataPackageType>::probeMesh”的声明 (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(172): note: 定义 (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(172): note: 'DataType SPH::MeshWithDataPackages<MeshFieldType,DataPackageType>::probeMesh(const SPH::Vecd &)' (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(172): note: 现有声明 (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)
2>F:\SPHinXsys-source\SPHINXsys\src\for_2D_build\meshes\mesh_with_data_packages.hpp(172): note: 'DataType SPH::MeshWithDataPackages<MeshFieldType,DataPackageType>::probeMesh(const SPH::Vecd &)' (编译源文件 F:\SPHinXsys-source\SPHINXsys\src\shared\geometries\level_set.cpp)

Need some help please.

**Comment by Xiangyu-Hu** [comment]
You error seems related to the following link.
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2244?view=msvc-170.
But SPHinXsys release or master branch should have not issue like it.

Please check the website tutorial for possible update of the installation.
The general experience is that failure installation usually caused by something (or step) missing.

**Comment by ChiZhangatTUM** [comment]
This can be closed.
