### ISSUE TITLE
DampingPairwiseWithWall throws "stack smashing" error if solid is higher resolution than fluid

### ISSUE THREAD

**Issue by BenceVirtonomy** [Xiangyu-Hu/SPHinXsys#150]
@Xiangyu-Hu @FabienPean-Virtonomy 

The maximum neighborhood size is exceeded here if the solid is higher resolution than the fluid. We access out-of-bounds array elements. There should at least be an exception for that before we get the stack smashing. A better solution could be to allocate a proper array size / use vector reserve + pushback?

![image](https://user-images.githubusercontent.com/78215583/189627727-1448f9cd-1240-4c31-8add-54f278c2ac7f.png)

**Comment by Xiangyu-Hu** [comment]
Yes. Actually, DampingPairwiseWithWall works only for single resolution.
Even we can avoid the runtime error, the result will not be right.
I will try to put a comment to the class.

**Comment by BenceVirtonomy** [comment]
Great, thank you!
