### ISSUE TITLE
use of Adaptive contact relations

### ISSUE THREAD

**Issue by TermeHansen** [Xiangyu-Hu/SPHinXsys#164]
I would like to use the Multi-level Mesh  to a problem similar to the `self_contact` or the `muscle_solid_contact test` but I am missing information on how to do:

`SelfSurfaceContactRelation` (Adaptive)

and the `InteractionDynamics` for 
`SelfContactDensitySummation`
`SelfContactForce`
`ContactDensitySummation`
`ContactForceFromWall`

with MultiLevel particles. Any help on how to work with this kind of system?

**Comment by Xiangyu-Hu** [comment]
Hi, @TermeHansen 
using adaptive resolution in SPHinXsys is still in its infancy. 
In the public repo, currently only flow simulation works.
In our internal repo, the solid dynamic without contact is in development.
Though it seems straightforward for extending the idea of adaptivity to contact dynamics,
We do not have sufficient human resource on it.
If you are interested in contribute on this topic, I would be happy to help you.

best regards,
Xiangyu

**Comment by TermeHansen** [comment]
Thank you very much for your feedback, it can well be that I will take up that task. I will let you know here if I get the time to take up this task.
