### ISSUE TITLE
Is there Outflow boundary condition in the code?

### ISSUE THREAD

**Issue by ccyx** [Xiangyu-Hu/SPHinXsys#19]
Is there Outflow boundary condition in the code?

**Comment by Xiangyu-Hu** [comment]
The team is working on it. It is involving with particle deletion, and is not very straightforward for implementation. However, it has be done in a feature branch in our internal developing repository, and will be merged to master and included in the new release.

**Comment by Xiangyu-Hu** [comment]
With the new updating (#44 pull request), the outflow boundary condition will be included. The new two examples are the T-shape channel and free-stream flow around cylinder. You are welcomed to test and evaluate, refactor and modify it.
