### ISSUE TITLE
FreeStreamVelocityCorrection not working properly in 3D

### ISSUE THREAD

**Issue by anastazja-bro** [Xiangyu-Hu/SPHinXsys#193]
FreeStreamVelocityCorrection in a 3D case is causing unexpected changes in the density distribution and incorrect velocity profile near the outlet #194 
![image](https://user-images.githubusercontent.com/117284531/215045239-0fd7b25e-b398-4bd7-abfe-0ce8d2178344.png)
![image](https://user-images.githubusercontent.com/117284531/215045535-963c1ead-417b-436c-92bf-955c45fb6f1e.png)

**Comment by YuVirtonomy** [comment]
The first picture is the result with FreeStreamVelocityCorrection  and the second picture is the result without FreeStreamVelocityCorrection.
With FreeStreamVelocityCorrection you can see at the end of x and y axis directions, the stream no longer points in the +X direction.

![WithFreeStreamVelocityCorrection](https://user-images.githubusercontent.com/111049554/215062821-27b18b25-d54d-46cd-9d36-0ca2bc342038.png)

![WithoutFreeStreamVelocityCorrection](https://user-images.githubusercontent.com/111049554/215063667-f7061376-061e-4123-abcd-3f14fcdc0c41.png)

**Comment by ShuoguoZhangTUM** [comment]
sorry, I can't analyze the causes only according to your pictures, if you can send me your C++ case file, I am pleased to help you.
my email address is shuoguo.zhang@tum.de

**Comment by YuVirtonomy** [comment]
Hii shuoguo,

This issue is related to the pull request #194 , you can click #194 to find the test case. Than you.

**Comment by ShuoguoZhangTUM** [comment]
I have read your code, I think the definition of the freestream velocity profile is wrong. Here is the code you write. 
target_velocity[0] = u_ave * (DH/2 - position[1]) * (DH/2 + position[1]) / DH / DH;
In 2D case, the velocity profile is defined by the position[0] and position[1].
but in 3D, there should also be a position[2] together to define the velocity profile. 
In 3d channel flow, both the velocity profile in xy and xz planes are parabolic.
however, your code only defines the parabolic profile in xy plane.

**Comment by anastazja-bro** [comment]
Hi Shuoguo,
The purpose of this case was to extend the 2D case, so the parabolic velocity profile was meant to be maintained only in xy plane, while in xz plane it's just part of the infinite flow, so it should be constant in z direction. 
The reason, why I needed the velocity correction is that the two z-normal walls were supposed to be removed and for now the only other way to simulate this case was to manually set velocity[2] of free surface particles to 0. Otherwise, there is no boundary condition on z-normal surfaces and the flow obviously goes to the sides.

**Comment by Xiangyu-Hu** [comment]
Please check the communications respect to the pull request for the solution of the issue.
