### ISSUE TITLE
Error in CorrectInterpolationKernelWeights

### ISSUE THREAD

**Issue by JohnVirtonomy** [Xiangyu-Hu/SPHinXsys#195]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/8d5a76089aedb3ce0d61a224b3858b85436c431c/SPHINXsys/src/shared/particle_dynamics/general_dynamics/general_interpolation.cpp#L52

@Xiangyu-Hu 
This is why the electromechanics case was failing
It had dW_ijV_j_ instead of W_ij_

**Comment by Xiangyu-Hu** [comment]
the correction is updated in the pull request.
