### ISSUE TITLE
Shell particles will collapse under large deformation

### ISSUE THREAD

**Issue by SchrodingersAlphaGo** [Xiangyu-Hu/SPHinXsys#208]
When the load of the 2d shell is a large value eg. 8000, the time step will decrease to a small value after some point suddenly without any obvious evidence, and the particles will collapse due to a large stress of some particles as the figures shows. However, when the load of the 2d shell is a relatively small value such as 500, the simulation will have a resonable results. 
See  [test_2d_shell_large_deformation](https://github.com/Xiangyu-Hu/SPHinXsys/tree/shell_test_with_large_deformation/tests/2d_examples/test_2d_shell_large_deformation) in branch [shell_test_with_large_deformation](https://github.com/Xiangyu-Hu/SPHinXsys/tree/shell_test_with_large_deformation).

![image](https://user-images.githubusercontent.com/45205564/219615815-036db243-8aac-42bf-a5a4-1dc2c4531c4c.png)
![image](https://user-images.githubusercontent.com/45205564/219613930-371a2ec6-9003-49fb-ac27-b1b892025ff9.png)
![image](https://user-images.githubusercontent.com/45205564/219615512-4bbf6a08-aba6-4f79-9803-42f1037c7532.png)

**Comment by DongWuTUM** [comment]
Hello,
I think the load is too great and exceeds the physical range. Do you have the reference which I can refer? And then I will do more check.

**Comment by SchrodingersAlphaGo** [comment]
We first encountered this problem in [test_3d_arc](https://github.com/Xiangyu-Hu/SPHinXsys/tree/master/tests/3d_examples/test_3d_arch), this case can refer to [Efficient meshless SPH method for the numerical modeling of thick shell structures undergoing large deformations](https://doi.org/10.1016/j.ijnonlinmec.2014.04.009) (Fig.18) and [Red blood cell simulation using a coupled shell–fluid analysis purely based on the SPH method](https://link.springer.com/article/10.1007/s10237-018-1085-9) (Fig.4).

**Comment by DongWuTUM** [comment]
Thank you for your information.
In the Refs., the load F is applied on the middle point or line of the arch. In this way, the results of applying Gravity is different with that of Refs. Could you try to apply force on the middle line of the test_3d_arch?

**Comment by SchrodingersAlphaGo** [comment]
We have tested it with force on the midline and come to the same conclusion. Particles will collapse.

**Comment by DongWuTUM** [comment]
Could you also upload this case?

**Comment by SchrodingersAlphaGo** [comment]
We've uploaded the case. You can check it now.
[test_3d_arch_force_on_midline](https://github.com/Xiangyu-Hu/SPHinXsys/tree/shell_test_with_large_deformation/tests/3d_examples/test_3d_arch_force_on_midline)

**Comment by DongWuTUM** [comment]
Thank you! 
I have thoroughly checked and tested it, and have summarized my findings below:

1. When lambda equals 10, the displacement of the arch's centroid is approximately 60 mm, which aligns with the results in the references.

2. There exists a critical load beyond which the centroid displacement jumps from around 60 mm to approximately 210 mm, as observed in the references. This indicates that the simulation must be collapsed if a large load is imposed.

3. The references mention the use of displacement control to simulate the presence of snap-through behavior in the load-displacement curve. In order to obtain accurate results, we need to follow the references' methodology for imposing the displacement. I would appreciate it if you could try the references' method and share your results with me.

Please let me know if you have any questions or concerns.

**Comment by SchrodingersAlphaGo** [comment]
Thanks for your reply!
In the reference, there is no detailed description of displacement control, so it will be difficult to implement. What confuses me is why the particles crash when the load is relatively large. 
In addition, I used ABAQUS to simulate the case **test_3d_arch** with a gravity load 900000, and ABAQUS can give a plausible result, as shown in the figure below. However, the particles of SPH will collapse under the same load. We think the key factor of this problem is the extent of the deformation rather than the displacement control. 
![image](https://user-images.githubusercontent.com/45205564/221535035-664a7ddb-926b-4f59-af62-17ce30bb7f4c.png)
![image](https://user-images.githubusercontent.com/45205564/221535248-a60520a4-8822-425b-80c8-d16b54fa83a0.png)

**Comment by Xiangyu-Hu** [comment]
Are you using implicit method? As there is a snap through, so the explicit solver may has some difficulties.

**Comment by DongWuTUM** [comment]
@SchrodingersAlphaGo Could you also share us the simulation video of Abaqus?

**Comment by SchrodingersAlphaGo** [comment]
The above result is using static method, and the result by explicit method is shown as follows.

![image](https://user-images.githubusercontent.com/45205564/221560580-0d3730a6-1508-482b-8f53-139516ea4689.png)



https://user-images.githubusercontent.com/45205564/221566271-9ed2b9cf-86af-4f1e-88ae-1f795e2b1c38.mp4

**Comment by DongWuTUM** [comment]
Thank you for providing this information!
After a thorough discussion, we think you are correct, and we will impose the displacement control and investigate the issues further.

**Comment by SchrodingersAlphaGo** [comment]
Thanks for your help! Looking forward to your correct version.

**Comment by Xiangyu-Hu** [comment]
It seems that the updating the rotation leads to the instability. we will revise it and have a close check.
