### ISSUE TITLE
SpiltandMerge bug

### ISSUE THREAD

**Issue by YuVirtonomy** [Xiangyu-Hu/SPHinXsys#221]
Vecu(index_i, particle_real_number) doesnt work for 3D

https://github.com/Xiangyu-Hu/SPHinXsys/blob/0accba677d75d9e8a04c163988e2dc3c2bc2b689/SPHINXsys/src/shared/particle_dynamics/general_dynamics/general_dynamics_refinement.cpp#L339

**Comment by Xiangyu-Hu** [comment]
a pull request solved this issue. #222
