### ISSUE TITLE
xsimd from VCPKG notable to comiple 

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#230]
this branch not able to compile xsimd test case
https://github.com/Xiangyu-Hu/SPHinXsys/tree/xiangyu/xsimd_update

**Comment by FabienPean-Virtonomy** [comment]
It is compiling and passing on the branch xsimd_update after some minor changes in the CI workflow file, see https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/4576466846. It has the same issue for Windows as in #231 though, some upstream issues to investigate.
