### ISSUE TITLE
vcpkg install failed

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#231]
#229 
VCPKG install failed due to not bale to install gfortran.

**Comment by FabienPean-Virtonomy** [comment]
Depends on upstream fixes: https://github.com/microsoft/vcpkg/pull/30546
I will test a PR setting the commit hash version directly, but otherwise should wait for a release which should come soon

**Comment by Xiangyu-Hu** [comment]
Is this a temporary solution only?
