### ISSUE TITLE
Xsimd using VCPKG leads to compiling errors

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#234]
In file included from /home/genre/SPHinXsys/tests/unit_tests_src/shared/xsimd_sphinxsys/test_xsimd_eigen/test_xsimd_eigen.cpp:1:
/home/genre/SPHinXsys/SPHINXsys/src/shared/xsimd_sphinxsys/xsimd_eigen.h: In function ‘SPH::RealX SPH::gatherRealX(SPH::StdLargeVec<double>&, size_t*) [with int XSIMD_SIZE = 4; SPH::RealX = xsimd::batch<double, xsimd::avx>; SPH::StdLargeVec<double> = std::vector<double, tbb::detail::d1::cache_aligned_allocator<double> >; size_t = long unsigned int]’:
/home/genre/SPHinXsys/SPHINXsys/src/shared/xsimd_sphinxsys/xsimd_eigen.h:63:98: error: no matching function for call to ‘xsimd::batch<double, xsimd::avx>::batch(__gnu_cxx::__alloc_traits<tbb::detail::d1::cache_aligned_allocator<double>, double>::value_type&, __gnu_cxx::__alloc_traits<tbb::detail::d1::cache_aligned_allocator<double>, double>::value_type&, __gnu_cxx::__alloc_traits<tbb::detail::d1::cache_aligned_allocator<double>, double>::value_type&, __gnu_cxx::__alloc_traits<tbb::detail::d1::cache_aligned_allocator<double>, double>::value_type&)’
   63 |         return RealX(input[*index], input[*(index + 1)], input[*(index + 2)], input[*(index + 3)]);
      |                                                                                                  ^
In file included from /home/genre/vcpkg/installed/x64-linux/include/xsimd/xsimd.hpp:29,
                 from /home/genre/SPHinXsys/SPHINXsys/src/shared/xsimd_sphinxsys/xsimd_eigen.h:39,
                 from /home/genre/SPHinXsys/tests/unit_tests_src/shared/xsimd_sphinxsys/test_xsimd_eigen/test_xsimd_eigen.cpp:1:
/home/genre/vcpkg/installed/x64-linux/include/xsimd/types/xsimd_batch.hpp:201:9: note: candidate: ‘template<long unsigned int ...Is> xsimd::batch<T, A>::batch(const T*, std::index_sequence<_Ind ...>)’
  201 |         batch(T const* data, detail::index_sequence<Is...>) noexcept;
      |         ^~~~~
/home/genre/vcpkg/installed/x64-linux/include/xsimd/types/xsimd_batch.hpp:201:9: note:   template argument deduction/substitution failed:
In file included from /home/genre/SPHinXsys/tests/unit_tests_src/shared/xsimd_sphinxsys/test_xsimd_eigen/test_xsimd_eigen.cpp:1:
/home/genre/SPHinXsys/SPHINXsys/src/shared/xsimd_sphinxsys/xsimd_eigen.h:63:98: note:   mismatched types ‘std::integer_sequence<long unsigned int, _Idx ...>’ and ‘double’
   63 |         return RealX(input[*index], input[*(index + 1)], input[*(index + 2)], input[*(index + 3)]);
      |                                                                                                  ^
In file included from /home/genre/vcpkg/installed/x64-linux/include/xsimd/xsimd.hpp:29,
                 from /home/genre/SPHinXsys/SPHINXsys/src/shared/xsimd_sphinxsys/xsimd_eigen.h:39,
                 from /home/genre/SPHinXsys/tests/unit_tests_src/shared/xsimd_sphinxsys/test_xsimd_eigen/test_xsimd_eigen.cpp:1:
/home/genre/vcpkg/installed/x64-linux/include/xsimd/types/xsimd_batch.hpp:453:12: note: candidate: ‘xsimd::batch<T, A>::batch(xsimd::batch<T, A>::register_type) [with T = double; A = xsimd::avx; xsimd::batch<T, A>::register_type = __vector(4) double]’
  453 |     inline batch<T, A>::batch(register_type reg) noexcept
      |            ^~~~~~~~~~~
/home/genre/vcpkg/installed/x64-linux/include/xsimd/types/xsimd_batch.hpp:453:12: note:   candidate expects 1 argument, 4 provided
/home/genre/vcpkg/installed/x64-linux/include/xsimd/types/xsimd_batch.hpp:441:12: note: candidate: ‘xsimd::batch<T, A>::batch(const xsimd::batch_bool<T, A>&) [with T = double; A = xsimd::avx]’

Wierd compling errors suggested that functions are defined.

**Comment by Xiangyu-Hu** [comment]
I have also tried to updated the VCPKG. the version ox xsimd is 8,1.

**Comment by FabienPean-Virtonomy** [comment]
Then your vcpkg installation is not really updated because the xsimd version upstream is 9.0.1, see https://github.com/microsoft/vcpkg/blob/master/ports/xsimd/vcpkg.json

The CI is with xsimd is passing for Linux and macOS, see #235 . It is failing on Windows seemingly due to some internal compiler error on valid deducible template parameter with Eigen (https://developercommunity.visualstudio.com/t/Template-argument-deduction-with-default/10283377)

You must checkout your vcpkg to master or to the commit merged recently https://github.com/Xiangyu-Hu/SPHinXsys/blob/ec818ab265fa13cdd6b4145831274b1538e10f2b/.github/workflows/ci.yml#L14

Then run something like this in your vcpkg folder
```bash
./bootstrap.sh
./vcpkg upgrade xsimd --no-dry-run
```

**Comment by Xiangyu-Hu** [comment]
Thanks. It seems that with the nearest VCPKG, it works.
Xiangyu
