### ISSUE TITLE
Regression test incapable to catch severe regression: impact on a FSI example

### ISSUE THREAD

**Issue by FabienPean-Virtonomy** [Xiangyu-Hu/SPHinXsys#236]
Version [v1.0-beta.0.7](https://github.com/Xiangyu-Hu/SPHinXsys/releases/tag/v1.0-beta.0.7) with changelog:

> Riemann solver will still be used for fluid-wall interaction, since some cases occasionally lead to very small times steps,
especially when the resolution is high.

introduced in commit https://github.com/Xiangyu-Hu/SPHinXsys/pull/211/commits/716ed06961f372b93cfd23da140ac8c1025ca171 via PR #211 is erroneous.

The example `test_2d_elastic_gate` yields the following results with current changes (blue lines, other colors are alternative variation of the fix in #237)
![image](https://user-images.githubusercontent.com/99172565/233020110-53a13b9c-6f0e-4a7b-b784-3ba4b93054b9.png)

This failure highlights a major problem and several minor ones:

1. ❗ The regression tests was unable to catch such error ❗ 
2. The PR lacked information: what commit or change was it reverting to (to enable easier comparison from review) and was conflated with several other changes. The change on those algorithmic kernels were bounded but with significant impact.
3. The review lacked diligence from experts who approved.

**Comment by Xiangyu-Hu** [comment]
@Bo-Zhang1995 could you have a look on this issue?

**Comment by Bo-Zhang1995** [comment]
As I checked, the maximum distance is only 0.7, but from the figure, the distance between the blue one and any other colors is greatly more than such distance. It is strange, and I will go further to check.

**Comment by Bo-Zhang1995** [comment]
The newly obtained result is much longer than that in the database, and we use the window band DTW algorithm with a window size equal to the difference between two lengths. This will lead to the DTW matrix being full of zero. This problem can be solved by regenerating the database, and I will also add a checking to avoid this happening again.

**Comment by Bo-Zhang1995** [comment]
The new version code generates a similar length result compared with the database, thus, the main reason should be the time step in the wrong code is much tiny and yields a much longer result, but the regression test doesn't catch this difference. I will add another criterion to check whether the length has much difference. When the result length has changed so much, the time step should has large changes, and something may be wrong.

**Comment by Bo-Zhang1995** [comment]
This issue may also occur in another two cases. 
2d_throat, 2d_two_phase_dambreak
I am trying to figure out them.

**Comment by Xiangyu-Hu** [comment]
This is done after revision on regression test function.
