### ISSUE TITLE
Too many warning in the code

### ISSUE THREAD

**Issue by chuvirtonomy** [Xiangyu-Hu/SPHinXsys#24]
I saw many warning like this during compiling:
/home/SPHinXsys/SPHINXsys/src/shared/particle_dynamics/solid_dynamics/solid_dynamics.cpp:247:3: warning:   when initialized here [-Wreorder]
This might have unexpected side effects. We should work together to resolve the issue.

**Comment by Xiangyu-Hu** [comment]
I have add -Werror=reorder in the cmake file in the bitbucket repo. Hopefully it will have less waring messages.

**Comment by chuvirtonomy** [comment]
I have solved all by this PR: https://github.com/Xiangyu-Hu/SPHinXsys/pull/30
