### ISSUE TITLE
Introduce clang-format config file

### ISSUE THREAD

**Issue by FabienPean-Virtonomy** [Xiangyu-Hu/SPHinXsys#253]
A `.clang-format` would be good to have in the root folder of the repo to enforce common style and ultimately reducing noise in PRs.

The default format you use with VS Code is described here https://code.visualstudio.com/docs/cpp/cpp-ide#_code-formatting

And has the following parameters:

```
UseTab: (VS Code current setting)
IndentWidth: (VS Code current setting)
BreakBeforeBraces: Allman
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
```

This addition should be then followed by a PR containing the whole repository processed by clang-format which will likely generate a lot of changes to adapt all files to the format.

**Comment by Xiangyu-Hu** [comment]
I have did it for the new pull request. #251
