### ISSUE TITLE
Update Lagrangian formulation using initial configuration only

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#263]
Using initial configuration only for solid dynamics but the formulation is relying on Cauchy stress and updated configuration which is deformed from the initial configuration. 
In this way, the physics assumptions can be applied in a straightforward way.

**Comment by Xiaojingtang1234** [comment]
for the convergency verification compared with the test_2d_oscillating_beam
![convergency](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/ae6b58e4-6444-4df9-9709-45c459f718bb)

**Comment by Xiangyu-Hu** [comment]
The result seems correct. However, I find that there is J missed in the formulation.

**Comment by DongWuTUM** [comment]
> The result seems correct. However, I find that there is J missed in the formulation.

@Xiangyu-Hu Because rho_, rather than rho0_, is used in the governing equation, J is no longer required.
