### ISSUE TITLE
Include the work on Laguree Gauss kernel test case

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#273]
To show that such kernel is good for Eulerian and solid problems.

**Comment by ZhentongWang** [comment]
I make a comparison between Wendland kernel and Laguerre Gauss kernel, and have some shortcomings. and I use the Eulerian flow around a cylinder to compare.

when i use Wendland kernel, I don't extra numerical dissipation from the Riemann solver ,i.e just viscous force in the simulation.
Firstly , I try the CFL=0.6 and the velocity contour is 
![wendland_0 6](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/df1f3fe0-323d-4661-8e5d-e0ff10398b35)

Then I set the CFL =0.3 and the velocity contour is 
![wendland_0 3](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/a0027e96-4a52-4672-a688-4e48b8d4550e)

so in this condition, CFL=0.3 is good choice for the simulation with the Wendland kernel.

After that, I switch the Wendland kernel to the Laguerre Gauss kernel .
When CFL=0.6, the result is 
![LG_0 6](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/168b7a39-d670-4264-9fa9-a1f1e307bec6)

When CFL=0.3, the result is 
![LG_0 3](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/01d0b077-b97f-4149-89cc-e19c53d6eba5)

When CFL=0.2, the result is 
![LG_0 2](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/d3f0a912-e687-4f1e-ab59-a40baa390f14)

so comparing these two kernels, seems like the Laguerre Gauss kernel require smaller CFL value than the Wendland kernel
