### ISSUE TITLE
Enhance installation experience from Biofluid Mechanics class

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#275]
Documenting issues faced in the class will be helpful for future reference.

**Comment by FengWang3119** [comment]
1. The installation of VCPKG using PowerShell may not succeed due to some system problems, keep reporting "不是内部或外部命令，也不是可运行的程序或批处理文件。". Using GitBash can succeed.

**Comment by Xiangyu-Hu** [comment]
Do you install vcpkg or using vcpkg install 3rd party libraries?

**Comment by Xiangyu-Hu** [comment]
Is it possible for wrongly use of ".\bootstrap-vcpkg.bat". Note that using .\ other than ./ in linux.

**Comment by FengWang3119** [comment]
2. for out newest code, visual studio should be 2019 or newer, but on the website, it says 2017 or newer.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/118197034/8dc4847b-14c1-45f1-abaa-3bc94cef2042)
3. some students are confused about the difference between dynamic and static version, and don't know which one to choose
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/118197034/8fe5206f-62c5-4427-a3f6-5dd0cb325270)
4. directly copy all the statements to install the dependencies may lead to unknown errors, just copy the statement one by one may be better.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/118197034/ed9ac422-1c0b-4a3d-8e2b-91980bee4676)

**Comment by FengWang3119** [comment]
when install pybind11 in linux, we may need firstly install a sub-module of python3, the error message will guide us on how to install it.

**Comment by FengWang3119** [comment]
For linux, if use the VSCODE to do the first build process, the simbody and other libraries may not be found.
Directly inputing command can avoid this issue,

**Comment by Xiangyu-Hu** [comment]
I close the issue as the information is updated in installation page: https://www.sphinxsys.org/html/installation.html
