### ISSUE TITLE
Switch between double and float

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#277]
The code should have the option to run with double or float for float-point operation.

**Comment by Xiangyu-Hu** [comment]
@ChiZhangatTUM we should work on the issue with the assigned branch.

**Comment by Xiangyu-Hu** [comment]
@ChiZhangatTUM our discussion on this issue will be based on the new branch.

**Comment by ZhenxiZhao** [comment]
a

**Comment by ChiZhangatTUM** [comment]
This test is done?

**Comment by Xiangyu-Hu** [comment]
Nor yet. There still some issues with simbody.

**Comment by ChiZhangatTUM** [comment]
> Nor yet. There still some issues with simbody.

OK, I can have a look in the following days.

**Comment by Xiangyu-Hu** [comment]
@ChiZhangatTUM please have a look the assigned branch and corresponding pull request.

**Comment by Xiangyu-Hu** [comment]
@ChiZhangatTUM I think that we need to add a CI to test the single precision version of the code. For the first version, we need only make sure the compiling, say in Linux, is success.

**Comment by Xiangyu-Hu** [comment]
CI is done.
