### ISSUE TITLE
shortcoming of FVM due to the mesh quality

### ISSUE THREAD

**Issue by ZhentongWang** [Xiangyu-Hu/SPHinXsys#284]
Lid driven cavity and flow around cylinder
![lid_driven_cavity_velocity_contour_FVM](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/107fabf8-8e73-4ef3-91ed-a22914498eb7)
and
![flow_around_cylinder_FVM](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/54a11137-f62b-4bfd-9377-97b4d34a2899)

**Comment by Xiangyu-Hu** [comment]
@ZhentongWang do have a branch corresponding to the issue?

**Comment by Xiangyu-Hu** [comment]
It seems that the noise is due to paraview visualization, nor the FVM method.
