### ISSUE TITLE
Floating body test case seems not right

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#289]
The 2d floating body problem seems not right.
![Screenshot from 2023-05-18 16-08-23](https://github.com/Xiangyu-Hu/SPHinXsys/assets/37415154/4e97cbb2-9a70-4b67-a86c-548bfd6d10da)
There are quite some flow around the floating body.

**Comment by ncsalis** [comment]
I have updated the master and tested. In the mac system seems ok. 
![floating_body](https://github.com/Xiangyu-Hu/SPHinXsys/assets/56539341/49232838-f299-4cb5-864c-3905deb762e7)

I will also check in linux system.

**Comment by ncsalis** [comment]
Also in linux system is working ok. 
![floting_box](https://github.com/Xiangyu-Hu/SPHinXsys/assets/56539341/b8aa30ee-cc7a-4cf2-9190-8e42666e33d6)

Maybe the bug is for the windows system. For curiosity have you tried the 3D floating body case? (3D cases kept failing in the windows CI test for the pull request and I have increased the dtwdistance)

**Comment by ncsalis** [comment]
pull request #267

**Comment by Xiangyu-Hu** [comment]
I am using Linux system.  Let me check again.

**Comment by Xiangyu-Hu** [comment]
Which master did you do the above computation,  and the resolution?

**Comment by ncsalis** [comment]
I updated the master with today merge before running. The resolution used is L/20.

**Comment by Xiangyu-Hu** [comment]
It is strange. I am using rhe same master on Linux. Same resolution as the master.

**Comment by ncsalis** [comment]
I have tried with lower resolution (L/10) and solution diverges. Tomorrow I will search for possible reasons

![anim_l10](https://github.com/Xiangyu-Hu/SPHinXsys/assets/56539341/116f8e86-e470-4f6b-a40c-c60c623fedd2)

**Comment by Xiangyu-Hu** [comment]
I also use resolution L/20.

**Comment by ncsalis** [comment]
It is strange that does not work in different machines and/or with different resolution. Maybe tomorrow we can discuss it

**Comment by Xiangyu-Hu** [comment]
I have found that I am using Intel compiler.

**Comment by Xiangyu-Hu** [comment]
The problem may be due to some small number issue as difference compiler give quite different results.

**Comment by Xiangyu-Hu** [comment]
I mean probably origining from initial particle position.
