### ISSUE TITLE
cmake show the following fails with clang++ compiler of oneAPI

### ISSUE THREAD

**Issue by ChiZhangatTUM** [Xiangyu-Hu/SPHinXsys#298]
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Failed
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Failed

These test fails related with pybind11, while looks like does not effect the compilation of sphinxsys.

**Comment by Xiangyu-Hu** [comment]
I did not notice this. Are you using icx and icpx as compiler?

**Comment by Xiangyu-Hu** [comment]
I have also used clang++ as compiler, it seems ok too.

**Comment by ChiZhangatTUM** [comment]
> I did not notice this. Are you using icx and icpx as compiler?

The icx and icpx works fine for the cmake process. Clang and clang++ show this test fail, while work fine for the configure, build and test. I will have more insights on this issue.

**Comment by Xiangyu-Hu** [comment]
The master branch passes CI on Mac OS now.
