### ISSUE TITLE
nonisotropic kernel for diffusion

### ISSUE THREAD

**Issue by Xiaojingtang1234** [Xiangyu-Hu/SPHinXsys#300]
**non converged in both x and y direction**
**the reference of kernel , _paper "ADAPTIVE SMOOTHED PARTICLE HYDRODYNAMICS : METHODOLOGY. II. J. MICHAEL OWEN1 LLNL, "_**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/7af137bd-728a-443e-b696-27d0c505c65e)
 **the tensor formation of 2d:**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/dd15a07c-a006-4600-b184-7d3b2bc4a883)
**for B-cubline kernel**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/8f691d4c-d380-4a75-8e11-6135f1e4c49e)

**for Wenland kernel: (my conclusion)**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/1df94dd7-6e2b-4f3d-a9b3-d080e193072a)

** refer of SPH dissipative dynamics,  _https://sci-hub.hkvisa.net/10.1103/PhysRevE.67.026705_**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/5362ba06-b330-4fb3-af78-fd0464097374)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/493e7dcd-3a99-4c15-9b49-ef4947863cb9)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/890cd2a9-166b-49e6-b1d4-2969fc4b22cc)
@Xiangyu-Hu

**Comment by Xiangyu-Hu** [comment]
What is your conclusion?

**Comment by Xiaojingtang1234** [comment]
> What is your conclusion?

I do not make and try it out ....confusing..

**nonisotropic transform tensor : Vec2d kernel_vector = (1.0, 1.0 / ratio) , ratio can be  2.0, 3.0, 4.0...... transform_angle(1.0)**
 **the displacemetnt in formal parameter is posi-posj**

> Mat2d AnisotropicKernel<KernelType>::getCoordinateTransformationTensorG(Vec2d kernel_vector, Vec2d transform_angle)

             {
		Mat2d scaling_tensor = Mat2d(1.0 / (this->h_* kernel_vector[0]), 0.0, 0.0, 1.0 / (this->h_* kernel_vector[1]));
		Mat2d rotation_tensor = getTransformationMatrixFromAngle(transform_angle);
		Mat2d G_kernel_coordinate = rotation_tensor * scaling_tensor * (~rotation_tensor);
		return G_kernel_coordinate;
            }

**this is how i make eij in nonisotropic kernel** 

> Vec2d AnisotropicKernel<KernelType>::geteij(const Real& distance, const Vec2d& displacement) const

	{
		Vec2d transformed_displacement_ = this->h_ * transformed_tensor_2d_ * displacement;
		return  transformed_tensor_2d_ * transformed_displacement_ / (( transformed_displacement_).norm() + TinyReal);
	}

**this is how  we get dw of nonisotropic ,** 

> Real AnisotropicKernel<KernelType>::dW(const Real& r_ij, const Vec2d& displacement) const

	{
		Vec2d transformed_displacement = transformed_tensor_2d_ * displacement;
		Real q = transformed_displacement.norm();
		return this->factor_dW_2D_ * this->dW_2D(q);
	}
> factor_dW_2D_= this->h_ *  this->h_ * det(transformed_tensor_2d_) * this->FactorW2D();
FactorW2D() : factor_W_2D_ = inv_h_ * inv_h_ * 7.0 / (4.0 * Pi);

**correspond to this formulation** 

![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/5fa0e874-0755-41dc-8e01-245e8d20f529)

**Comment by Xiaojingtang1234** [comment]
**Google test ; this is when Laplacian equals to 2,  saturation = x*x, while when   saturation = y*y, Laplacian around 0.01**

    TEST(test_anisotropic_kernel, test_rij)
    {
	 int y_num = 8;
	Real PH = 1.0;
	Real ratio_ = 4.0;
	Real PL = ratio_* PH;

	Vec2d scaling_vector = Vec2d(1.0, 1.0 / ratio_);
	Real resolution_ref = PH / Real(y_num);
	Real resolution_ref_large = ratio_ * resolution_ref;
	int x_num = PL / resolution_ref_large;
 
 
	AnisotropicKernel<KernelWendlandC2>  wendland(1.15 * resolution_ref_large, scaling_vector,  Vec2d(0.0));
	Real second_order_rate = 0.0;
	Real sum = 0.0;
	Vec2d first_order_rate =Vec2d(0.0) ;
	Vec2d center = Vec2d(resolution_ref_large * 4.0, resolution_ref *4.0);
 

	Real V_ = resolution_ref * resolution_ref_large;
	
       for (int i = 0; i < (x_num + 1); i++)
	   {
		for (int j = 0; j < (y_num + 1); j++)
		{
			Real x = i * resolution_ref_large;
			Real y = j * resolution_ref;
			
		 
			Vec2d displacement =  center - Vec2d(x, y) ;
			Real distance_ = displacement.norm();
		
		
			Real  sarutration_ = 1.0 * x * x;
			Real  sarutration_center = 1.0 * center[0] * center[0];


			if (wendland.checkIfWithinCutOffRadius(displacement))
			{
				Vec2d  eij_dwij_V = wendland.geteij(distance_, displacement)* wendland.dW(distance_, displacement) * V_;
				
				sum += wendland.W(distance_, displacement)* V_;
				first_order_rate -= (sarutration_center - sarutration_)* eij_dwij_V;

				second_order_rate +=  2.0 * (sarutration_center - sarutration_)  * dot(displacement, wendland.geteij(distance_, displacement) )
				            /  (wendland.getrij(distance_, displacement) + TinyReal)
					    * wendland.dW(distance_, displacement) * V_ * 1.0 / (wendland.getrij(distance_, displacement)+ TinyReal);
			}		
		}

	}
	

	EXPECT_FLOAT_EQ(1.0, sum); 
	EXPECT_EQ(2.0, second_order_rate);


}

**Comment by Xiaojingtang1234** [comment]
**I checked Paul W. Cleary∗ and Joseph J. Monaghan† paper, and use equation 16 with q = transformed_displacement = transformed_tensor_2d_ * displacement; it does not work right**.
I did not find any other direct materials that have concluded this  Laplacian in nonisotropic kernel

https://sci-hub.hkvisa.net/10.1006/jcph.1998.6118

![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/bc075d4d-4c40-4079-8253-a91ac28a12dd)

**Comment by Xiangyu-Hu** [comment]
We may try to derive by find the relation factor between isotropic and anisotropic laplacian in its analytical form first. Then apply this relation to the numerical formulation.

**Comment by Xiangyu-Hu** [comment]
We may try to derive by find the relation factor between isotropic and anisotropic laplacian in its analytical form first. Then apply this relation to the numerical formulation.

**Comment by Xiangyu-Hu** [comment]
Could you make a branch with only the anisotropic kernel and the Google test?

**Comment by Xiaojingtang1234** [comment]
sure, i am making

**Comment by Xiaojingtang1234** [comment]
refer :  https://iopscience.iop.org/article/10.1086/313100/pdf
https://sci-hub.hkvisa.net/10.1007/s00466-004-0620-y

**Comment by Xiangyu-Hu** [comment]
Here is my derivation of the ASPH kernel approximations.
![Screenshot from 2023-05-25 18-28-31](https://github.com/Xiangyu-Hu/SPHinXsys/assets/37415154/b51ef4f0-94eb-43d3-8f1d-8f44c4d51b61)

**Comment by Xiaojingtang1234** [comment]
ok i will see , and i already pushed the documents and google test on the branch xiaojing-anisotropic  [https://github.com/Xiangyu-Hu/SPHinXsys/compare/master...Xiaojingtang1234:SPHinXsys-xiaojing:xiaojing-anisotropic](url)
I use another namespace to seperate the orginal kernel and my kernel.
Some funtions are virtual and `checkIfWithinCutOffRadius(Vec2d displacement) ;` should be written into base_kernel.h

**Comment by Xiangyu-Hu** [comment]
Please have a check on the new formulation and we can discuss it.

**Comment by Xiaojingtang1234** [comment]
I checked, it seems not right.  
I update this part  code in my branch according to my understanding.
if i understand correctly,    `2|G|G:G`  is  a scalar and the latter actually is the same with previous Laplacian discrization. it cannot modify the nonisotrpic nature in x and y direction.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/4797dcf7-2426-402c-b146-6ae27179abdc)

![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/5e807e55-ad2e-4a3b-bdbc-8b2b7081eff1)

**Comment by Xiangyu-Hu** [comment]
You can check if the derivation is wrong somewhere.

**Comment by Xiaojingtang1234** [comment]
could you update the new formulation?
it seems not right in code. i did not  find anything wrong.
need to check the theory formulation again

**Comment by Xiangyu-Hu** [comment]
![Screenshot from 2023-05-27 01-36-14](https://github.com/Xiangyu-Hu/SPHinXsys/assets/37415154/24d54b4d-1d1e-43f3-b3da-ae7d33a6f114)

**Comment by Xiaojingtang1234** [comment]
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/a92a2a45-3a49-4697-bea1-47e6e46ceae9).
![612103ae8fc67b8eeedcfcf924c0db9](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/25b76fb8-4847-4fb5-96c9-54004d6a6f09)

**Comment by Xiangyu-Hu** [comment]
Yes. There is 
Something wrong.

**Comment by Xiaojingtang1234** [comment]
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/8604e77c-8450-46b5-ad9b-6556389ac8b7)

![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/8b41b48d-6aef-41f2-b98b-f1482455203e)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/2c272b2b-f77e-4139-ac42-5adad1991966)

**Comment by Xiaojingtang1234** [comment]
It seems something wrong .
We still consider point (0,0) and (4, 1) for nonisotropic, T(r) = x^2+y^2,  then we have phi_ij = Phi_(0,0) - Phi_(4,1)   = 0- (4*4 -1*1) =-17.
but in isotropic case, it is   phi_ij =  Phi_(0,0) - Phi_(1,1)   = 0- (1*1 -1*1) =-2.
Weired number 17 cannot be modified by G^2 : phi_ij *Tensor;

**Comment by Xiangyu-Hu** [comment]
We do not need modify 17 to  2 for computing  the laplacian.

**Comment by Xiangyu-Hu** [comment]
Update the newest formulation. We can have a try.
![Screenshot from 2023-06-01 19-24-35](https://github.com/Xiangyu-Hu/SPHinXsys/assets/37415154/02a406b3-a993-4421-88da-b8cd576a6c66)

**Comment by Xiaojingtang1234** [comment]
I am more confused....i will try to have a try..
also checking how Laplacian operator works in  polar coordinates,
 trying to find the  relations of how different coordinates transform. Maybe we can get some useful information from polar coordinates

**Comment by Xiangyu-Hu** [comment]
Where is your confusing ?

**Comment by Xiaojingtang1234** [comment]
The result is bad. The profile is T =x^2
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/06e7ddb7-2a33-478d-b559-49511e60c7a3)

I checked my code implementation,  when it is isotropic, it works right.
i checked the tensor, it is right, dW is right.
 I put the code in the branch xiaojing_anisotropic kernel in SPHinxsys resposity, including the kernel. cpp and the google test.

**Comment by Xiaojingtang1234** [comment]
Note we refer this paper,    this is the reason why there is a h in G .
 https://iopscience.iop.org/article/10.1086/313100/pdf
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/f30caa00-3abd-46d3-9d44-8fb97ef82ed8)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/9097f9f0-774f-4f0f-8b11-7c8777ff7b00)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/ed92818e-c4ad-4af8-a6e3-063a497519b5)

**Comment by Xiaojingtang1234** [comment]
ok, i checke the code, 
at line 42 og test , we should use  `Vecd pos_i = Vecd(resolution_x * x_num / 2.0, resolution_y * y_num /2.0 ); // Particle i location`
to keep i is always at the center.
 Also i am wondering if we could first caculate the gradient T  and then caculate the  gradient gradient T. Hourglass may exist but it may work.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/121554318/647f006d-bfdb-47e6-a73d-f3b46119bd93)

**Comment by Xiangyu-Hu** [comment]
it is ok. We just use this formula and check the diffusion convergence.
