### ISSUE TITLE
Update installation instruction. 

### ISSUE THREAD

**Issue by DrChiZhang** [Xiangyu-Hu/SPHinXsys#302]
As pybind11 is required by the current version, installation instruction should be updated accordingly by add using vcpkg to install pybind11.

**Comment by maiyetum95** [comment]
Yes, I will do it.


________________________________
From: Chi Zhang ***@***.***>
Sent: 24 May 2023 11:50:22
To: Xiangyu-Hu/SPHinXsys
Cc: Mai Ye; Assign
Subject: [Xiangyu-Hu/SPHinXsys] Update installation instruction. (Issue #302)


As pybind11 is required by the current version, installation instruction should be updated accordingly by add using vcpkg to install pybind11.

**Comment by Xiangyu-Hu** [comment]
It is done in the new version.
