### ISSUE TITLE
A phenomenon in Eulerian framework 

### ISSUE THREAD

**Issue by ZhentongWang** [Xiangyu-Hu/SPHinXsys#307]
when I try the case of backward-facing step case with Re=400, I found out a phenomenon but I think this phenomenon also occur in other cases like flow around a cylinder case.
At beginning , I don't introduce the numerical dissipation from the Riemann problem, 
https://github.com/Xiangyu-Hu/SPHinXsys/blob/319520e02f631847f85160c0e8b55648c395eafa/tests/user_examples/ExtraSources/extra_sources_share/common_weakly_compressible_eulerian_classes.h#L93-L98
here, I set parameter in the limiter as 0, then we can see this not using Riemann solver. and the result of the velocity contour in this case is 
![limiter0_t_0 3](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/9fba5bc8-0550-4dc2-923e-0f335fe3d3ef)
and the acostic timestep is (https://github.com/Xiangyu-Hu/SPHinXsys/blob/319520e02f631847f85160c0e8b55648c395eafa/tests/user_examples/ExtraSources/extra_sources_share/common_weakly_compressible_eulerian_classes.cpp#L16-L19)

I have tried two approaches to solve this, 
first one is that increase the parameter in the limiter, and  I try parameters 5 and 10 in the limiter
![limiter5_t_0 3](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/9450039c-b2f9-4322-bfa5-4746cad10ab7) and 
![limiter10_t_0 3](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/b9407dca-5075-474c-99bf-68bd39dbe82a)
 as shown, there is a pattern when the parameter is low, this is also occurring in the flow around cylinder case , but we thought that as sound propagation before, but probably it is not. and with the increase of the parameter in the limiter, the pattern is dissapearing gradually.

Second one is that I decrease the acostic timestep (parameter in the limiter is also 0) ,
I use the equation like this 0.5*(0.6 / Dimensions * smoothing_length_min_ / (reduced_value + TinyReal);) and the result is like 
![limiter0_t_0 15](https://github.com/Xiangyu-Hu/SPHinXsys/assets/126269817/8e01115f-de50-48f6-adf0-6b69b09d6fd3)
 the pattern is not showing in this situation. 

Compared this two approaches, I think we could decrease the acoustic timestep a little bit cuz we could get higher accurate result in the low resolution. what do you think of this ? professor Hu

**Comment by ChiZhangatTUM** [comment]
High-order time integration may also be helpful to remove the noise.

**Comment by ZhentongWang** [comment]
> High-order time integration may also be helpful to remove the noise.
thanks for the advice. I will check that later

**Comment by Xiangyu-Hu** [comment]
I am wondering whether "set parameters to zero" means no or maximum numerical dissipation?

**Comment by Xiangyu-Hu** [comment]
> > I am wondering whether "set parameters to zero" means no or maximum numerical dissipation?
> 
> means no numerical dissipation from the Riemann solver

Does it means no riemann solver.

**Comment by ZhentongWang** [comment]
> > > I am wondering whether "set parameters to zero" means no or maximum numerical dissipation?
> > 
> > 
> > means no numerical dissipation from the Riemann solver
> 
> Does it means no riemann solver.

Yes. just using average value as middle state value

**Comment by Xiangyu-Hu** [comment]
Not sure the issue still there.
