### ISSUE TITLE
Maintenance: cleanup branches

### ISSUE THREAD

**Issue by FabienPean-Virtonomy** [Xiangyu-Hu/SPHinXsys#332]
The repository will soon reach 100 public branches on the repo. This is how it looks like
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/99172565/a5ece3cc-cfb7-4e40-a08d-01b6556e3304)

Recommended actions:
* Activate automatic deletion of merged branch in the repository settings
* Check and delete stale branches manually
* All created branches on this repo should some naming conventions with a "path", e.g. `feature/`, `fix/`, `dev/`

To be determined:
* Naming convention

**Comment by Xiangyu-Hu** [comment]
Ok, I can try to delete some old useless branches.

**Comment by yyc84** [comment]
I will move my old branches

**Comment by Xiangyu-Hu** [comment]
It seems that using forked repository to add new features is cleaner than direct use the main repository.

**Comment by Xiangyu-Hu** [comment]
the number of branches have been monitored now.
