### ISSUE TITLE
No nonRiemannsolver for compressible flow in Eulerian SPH scheme.

### ISSUE THREAD

**Issue by Bo-Zhang1995** [Xiangyu-Hu/SPHinXsys#335]
Currently, it seems that only the HLLC Riemann solver with and without a limiter for the compressible flow is in the Eulerian SPH scheme.
It should include a non-Riemann solver as well for better testing of more cases.

**Comment by Xiangyu-Hu** [comment]
@ZhentongWang please consider this issue.

**Comment by ZhentongWang** [comment]
Sure, I will add the non-Riemann solver for compressible framework soon.

**Comment by Xiangyu-Hu** [comment]
@ZhentongWang I have created a branch for this issue. Please work on this branch directly.

**Comment by Xiangyu-Hu** [comment]
the issue is close due to the merged pull request #337
