### ISSUE TITLE
Separated time integrater for FVM? 

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#339]
I think that we do not need separated time integrate for FVM method.
The FVM and SPH method should share exact the same algorithm, except with different value in the configurations.
The current  formulation is redundant.

**Comment by Xiangyu-Hu** [comment]
This issue should solved together with the pull request #326.

**Comment by Xiangyu-Hu** [comment]
This issue is still not solved yet.

**Comment by ZhentongWang** [comment]
> This issue is still not solved yet.

I am still thinking how to separate those well and I will try to finish that soon.

**Comment by Xiangyu-Hu** [comment]
As pull request done.  I close the issue.
