### ISSUE TITLE
out put path bug

### ISSUE THREAD

**Issue by ChiZhangatTUM** [Xiangyu-Hu/SPHinXsys#359]
**Describe the bug**
there is a bug of BodyStatesRecordingToVtp, the output path is not correctly set. 

In line 17 of io_vtk.cpp, the output path is set as:
std::string filefullpath = io_environment_.output_folder_ + body->getName() + "_" + sequence + ".vtp",
while the correct path is 
std::string filefullpath = io_environment_.output_folder_ + "/" + body->getName() + "_" + sequence + ".vtp";

**Comment by Xiangyu-Hu** [comment]
Sorry. I will change it now.

**Comment by Xiangyu-Hu** [comment]
@ChiZhangatTUM  Actually, you can correct directly and give a fast pull request for this type of issues.

**Comment by ChiZhangatTUM** [comment]
> @ChiZhangatTUM Actually, you can correct directly and give a fast pull request for this type of issues.
Understood.

**Comment by ChiZhangatTUM** [comment]
Close.
