### ISSUE TITLE
Invalid numeric argument '/Werror' while building

### ISSUE THREAD

**Issue by ngkhaiching2000** [Xiangyu-Hu/SPHinXsys#36]
Hi SPHinXsys team, 

I'm now trying out the feature of SPHinXsys (following the YouTube Installation procedure) & I encountered the following issue while building the Test_2D_dambreak case. 

Error code D8021 : Invalid numeric argument '/Werror' while building

From the web, this error code D8021 states: 
invalid numeric argument 'number'
A number greater than 65,534 was specified as a numeric argument.

I am not sure how to resolve this. 

Can you advise? Thank you very much sphinxsys team.

**Comment by Xiangyu-Hu** [comment]
You can just delete -Werror in line 38 CMakeLists.txt in the repo folder. This compile switch only works for  linux.

**Comment by ngkhaiching2000** [comment]
Thanks Prof. I will comment these 2 lines.
    #SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" " -Werror /MP")
    #set(CMAKE_CXX_FLAGS "-Wall -Werror -std=c++11 -DUNIX -

**Comment by Xiangyu-Hu** [comment]
NO, You need delete "-Werror" not comment these lines. Otherwise, it will not compile in right way.

**Comment by Xiangyu-Hu** [comment]
Only in line 38.

**Comment by ngkhaiching2000** [comment]
Hi Prof, 
I've deleted -Werror on line 38. I can able to build the "test_2d_poiseuille" project in "Release" mode now.

I've tried to build the same project in "Debug" mode as well; unfortunately I am getting the error like this:
C1128	number of sections exceeded object file format limit: compile with /bigobj	sphinxsys_static_2d	  C:\Research\SPHinXsys-master\SPHINXsys\src\for_2D_build\geometries\geometry.cpp

C1128	number of sections exceeded object file format limit: compile with /bigobj	sphinxsys_2d
C:\Research\SPHinXsys-master\SPHINXsys\src\for_2D_build\geometries\geometry.cpp

LNK1104	cannot open file '..\..\..\SPHINXsys\lib\Debug\sphinxsys_2d.lib'	test_2d_poiseuille_flow
Link

I've changed the cmake_build_type in cmake to "Debug" as well, same errors are obtained.

May I know whether you came across the above errors?

**Comment by Xiangyu-Hu** [comment]
It seems that it is an error with Visual Studio. We did see this before. Could try to build with ReleaseWithDebugInfo?
Could you begin with new issue, as this is not relevant to -Werror anymore.
