### ISSUE TITLE
Generating wall (solid body) from particles on surface of stl

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#361]
### Discussed in https://github.com/Xiangyu-Hu/SPHinXsys/discussions/352

<div type='discussions-op-text'>

<sup>Originally posted by **Nadun19** June 30, 2023</sup>
I am following the "Example 3: 3D Multi-resolution isotropic particle distribution of complex geometries" to generate SPH particles with an STL file. I was wondering what is the best approach to separate the FluidBody and SolidBody (Wall boundary), which is defined based on the outer surface SPH particles. So the inside SPH particles form the FluidBody. 

Thanks,
Nadun</div>

**Comment by ChiZhangatTUM** [comment]
In this case, how many layers of particles is treated as solid boundary?

**Comment by Xiangyu-Hu** [comment]
it is parameter you can choose.

**Comment by Nadun19** [comment]
Is it possible to use the ExtrudeShape on the TriangleMeshShapeSTL shape type? It did not seem to compile when I tried modifying the 3d_particle_relaxation_single_resolution example.

**Comment by Xiangyu-Hu** [comment]
It should be OK. As the new class is a template class. You can create a branch on your proposed case and a new issue or draft pull request, so that we an have a look on the case.
