### ISSUE TITLE
The problem of gas-liquid two-phase flow

### ISSUE THREAD

**Issue by BIANJINGALUN** [Xiangyu-Hu/SPHinXsys#365]
The following problems have arisen in the operation of the gas-liquid two-phase flow that we want to achieve:

1. we first arrange the distribution of gas-liquid particles to achieve a cylindrical periodic boundary

![particle distribution](https://github.com/Xiangyu-Hu/SPHinXsys/assets/103891168/93aed239-3421-4aa3-8514-b30ab59e8318)

2. After we run a few steps, we visualize the results of the run and find that both gas particles and liquid particles are beyond the solid boundary
![escape](https://github.com/Xiangyu-Hu/SPHinXsys/assets/103891168/21d02121-755d-4f0c-b7ee-a8f5c730d69f)
3. Not all the particles go beyond the boundary and then return to the buffer

Is there anyone who has the same problem?
How can I solve it? Thank you for your help！
The specific procedure is as follows:
[code.txt](https://github.com/Xiangyu-Hu/SPHinXsys/files/11999129/code.txt)

**Comment by Xiangyu-Hu** [comment]
@BIANJINGALUN 

Thanks for the issue.
You need make your case publicly accessible first through github .
I.e. you need make it a branch in you forked repository.

Best wishes,
Xiangyu

**Comment by BIANJINGALUN** [comment]
Ok, thanks for the warning, Miss Hu
I'm using github for the first time and may not be familiar with it, but I've made the examples public

**Comment by BIANJINGALUN** [comment]
Ok, thank you Professor Hu for reminding me
This is my first time using github and I may not be familiar with it, but I have now made the case public

**Comment by Xiangyu-Hu** [comment]
Could you refer here to your public branch, so that we can have a look on it?

**Comment by ChiZhangatTUM** [comment]
@BIANJINGALUN Any update? Did you test you case in 2D?

**Comment by Xiangyu-Hu** [comment]
no response from the sender of the issue.
