### ISSUE TITLE
Unable to reproduce droplet oscillation results from Adami et. al (2010)

### ISSUE THREAD

**Issue by nilot-pal** [Xiangyu-Hu/SPHinXsys#378]
Hi all,
I was trying to reproduce the 2d droplet oscillation results presented in the following two papers:
1. Hu, X. Y., & Adams, N. A. (2006). A multi-phase SPH method for macroscopic and mesoscopic flows. Journal of Computational Physics, 213(2), 844-861.
2. Adami, S., Hu, X. Y., & Adams, N. A. (2010). A new surface-tension formulation for multi-phase SPH using a reproducing divergence approximation. Journal of Computational Physics, 229(13), 5011-5021.
However, my results don't match exactly with the literature. Attached is a screenshot of the mismatch-:
![COM_pos_SPH_Hu_2010_vs_lit](https://github.com/Xiangyu-Hu/SPHinXsys/assets/72824334/281901ab-b2d8-4150-985e-784cf08f96e7)
I am using an earlier version of SPHinXsys with some modifications (you can find it here: https://github.com/nilot-pal/SPHinXsys-nilo.git) to incorporate classes for finding the COM position and time steps from the 2010 paper.
Please let me know your thoughts on this!

**Comment by ChiZhangatTUM** [comment]
Would you please also attach the particle distribution at t = 0, 0.08, 0.16, 0.26 and 0.5?

**Comment by nilot-pal** [comment]
**t=0**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/72824334/7aeae4de-dd10-445f-8d36-c25f1bc61403)
**t = 0.08**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/72824334/9b4c2528-009a-4af4-994b-fee3a4587edf)
**t = 0.16**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/72824334/7e7e2743-345e-446a-aed3-1dcbbb63cf29)
**t= 0.26**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/72824334/a9578e1f-1e52-44bb-a6d5-54b054cb62d5)
**t = 0.5**
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/72824334/3e547b38-7674-4518-91cf-26588b8dbfcc)

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang Could you take some time to have a look this issue?

**Comment by Shuaihao-Zhang** [comment]
> @Shuaihao-Zhang Could you take some time to have a look this issue?

We also found this problem before, refer to this issue #288.  @nilot-pal 

This is because the function `ReinitializedDensity` was changed in this pull request #274.

I haven't had much time to pay attention to this issue in the past few weeks. I will try to fix this later.

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang @nilot-pal Is in this case the air modeled?

**Comment by nilot-pal** [comment]
@Xiangyu-Hu , yes air is modelled, I just hid that phase in paraview. I used the 2d square droplet deformation test case as reference for the air-water-wall interaction, if that helps.

**Comment by Xiangyu-Hu** [comment]
@nilot-pal Please have check the bug fix. Please try modify your case with this bug fix.

**Comment by Xiangyu-Hu** [comment]
![Screenshot from 2023-07-26 21-44-48](https://github.com/Xiangyu-Hu/SPHinXsys/assets/37415154/fd7954a7-19a2-4c91-8975-3c83734c5f6f)

**Comment by nilot-pal** [comment]
@Xiangyu-Hu , thanks. I incorporated your changes and ran the simulation again. In terms of the COM position, the results have improved as far as being close to literature data is concerned, i.e., droplet remains stable till 0.5 sec.
However, there is still some mismatch with the literature data (2006 paper) as we can see in the figure below.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/72824334/83ed86c2-19d3-454a-a350-44984713829a)

**Comment by Xiangyu-Hu** [comment]
@nilot-pal the current algorithm is neither the 2006 or 2010 version. It is a simplified version. We can have a further look on it. The worst case is we simply re-implement the old algorithm.

**Comment by nilot-pal** [comment]
@Xiangyu-Hu , thanks a lot for the clarification, because I was under the impression that the algo is from the 2010 paper.
Eventually, I want to simulate droplet impact on a solid surface and was trying to reproduce the droplet oscillation results from literature just to confirm if the surface tension model in SPHinXsys can reproduce some standard example problem.
Instead of implementing the old algorithm again, I am more interested to find out how to model surface tension that can handle droplet impact. 
So, if you want me to close this issue, I'll do it.

**Comment by Xiangyu-Hu** [comment]
@nilot-pal thanks for clarification.  Please toke some time on other things. We will solve issue as soon as possible.

**Comment by Xiangyu-Hu** [comment]
@nilot-pal Hi, there is a bug in  mulit-phase viscous acceleration and was corrected in the new pull request. Please have a try for your case.

**Comment by nilot-pal** [comment]
@Xiangyu-Hu , thanks. After incorporating changes as per #391, I got the following result:
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/72824334/fbfd695e-1ef5-4a69-ab31-09b6119b9854)

**Comment by Xiangyu-Hu** [comment]
Still need to work on it so that the simulation be stable in long time.

**Comment by Xiangyu-Hu** [comment]
@nilot-pal I have found the problem behind the issue, it is due to the wrongly imposed transport velocity formulation.
My simple ad hoc correction leas to very stable solution. I will update the new test soon.

**Comment by Xiangyu-Hu** [comment]
![myFile8-1-2023_121439_PM](https://github.com/Xiangyu-Hu/SPHinXsys/assets/37415154/f52ddb17-e2fa-45cc-a54c-06a0dc1a53e6)

**Comment by Shuaihao-Zhang** [comment]
Great! Seems much better!

**Comment by Xiangyu-Hu** [comment]
@nilot-pal please check the new version. I think that this version, is still not perfect, but should be be sufficient for your test.

**Comment by nilot-pal** [comment]
@Xiangyu-Hu, thanks a lot for your attention to this. New result after incorporating #398 is as follows:
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/72824334/b34345a6-7875-49f1-bf23-7ce67dc5b3c3)
As you said, the droplet oscillation is stable for longer time.

**Comment by Xiangyu-Hu** [comment]
@nilot-pal Great! Could you update the square_droplet case in repository with your  cases test. I think that your case is more comprehensive and easier to maintain as it has observed quantitates for regression test.

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang @nilot-pal We will continuously improve the surface tension model.

**Comment by Xiangyu-Hu** [comment]
Another formulation has very good stability,[https://youtu.be/r7SJ7mxoPFs](url)
