### ISSUE TITLE
Too loog CI time for test_3d_oscillating_plate_UL case

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#385]
Start  59: test_3d_oscillating_plate_UL
 59/108 Test  #59: test_3d_oscillating_plate_UL ...................................   Passed  1353.18 sec

It should be at most about 500 sec.

**Comment by Shuaihao-Zhang** [comment]
I tried to reduce the CI test time by minimizing the total calculation time, refer to this pull request #387
