### ISSUE TITLE
A problem in Dirichlet boundary condition for diffusion

### ISSUE THREAD

**Issue by WeiyiKong321** [Xiangyu-Hu/SPHinXsys#386]
Please check line 178 in diffusion_dynamics.hpp:
`
            this->all_diffusions_[m]->getInterParticleDiffusionCoff(particle_i, particle_j, e_ij);
`

`particle_j` is the index of a contact particle and cannot be used in function `getInterParticleDiffusionCoff`.

**Comment by WeiyiKong321** [comment]
@Xiangyu-Hu Prof. Hu, could you please add my account to collaborators? Thanks a lot : )

**Comment by ChiZhangatTUM** [comment]
> Please check line 178 in diffusion_dynamics.hpp: `this->all_diffusions_[m]->getInterParticleDiffusionCoff(particle_i, particle_j, e_ij);`
> 
> `particle_j` is the index of a contact particle and cannot be used in function `getInterParticleDiffusionCoff`.

Would do you please specify the branch you are working on?

**Comment by WeiyiKong321** [comment]
> > Please check line 178 in diffusion_dynamics.hpp: `this->all_diffusions_[m]->getInterParticleDiffusionCoff(particle_i, particle_j, e_ij);`
> > `particle_j` is the index of a contact particle and cannot be used in function `getInterParticleDiffusionCoff`.
> 
> Would do you please specify the branch you are working on?

That's from the master branch

**Comment by ChenxiZhaoTUM** [comment]
Hi Weiyi,
I have changed the getInterParticleDiffusionCoff() function of the Dirichlet wall boundary. (see the linked branch)

The diffusion coefficient of the diffusion process interacting with walls is unrelated to the wall boundary, so the old one getInterParticleDiffusionCoff(particle_i, particle_j, e_ij) tends to confuse the SPHinXsys users.
The new one getInterParticleDiffusionCoff(particle_i, particle_i, Vecd::Zero()) is more clear that the diffusion coefficient in this process (diffusion body contacted with Dirichlet boundary) has nothing to do with the contact walls.

For the diffusion part, we just have done the diffusion body interacting with the wall boundaries. Later, we will do the diffusion process referring to the interaction between two diffusion bodies.

**Comment by WeiyiKong321** [comment]
> Hi Weiyi, I have changed the getInterParticleDiffusionCoff() function of the Dirichlet wall boundary. (see the linked branch)
> 
> The diffusion coefficient of the diffusion process interacting with walls is unrelated to the wall boundary, so the old one getInterParticleDiffusionCoff(particle_i, particle_j, e_ij) tends to confuse the SPHinXsys users. The new one getInterParticleDiffusionCoff(particle_i, particle_i, Vecd::Zero()) is more clear that the diffusion coefficient in this process (diffusion body contacted with Dirichlet boundary) has nothing to do with the contact walls.
> 
> For the diffusion part, we just have done the diffusion body interacting with the wall boundaries. Later, we will do the diffusion process referring to the interaction between two diffusion bodies.

Thanks

**Comment by ChiZhangatTUM** [comment]
> Hi Weiyi, I have changed the getInterParticleDiffusionCoff() function of the Dirichlet wall boundary. (see the linked branch)
> 
> The diffusion coefficient of the diffusion process interacting with walls is unrelated to the wall boundary, so the old one getInterParticleDiffusionCoff(particle_i, particle_j, e_ij) tends to confuse the SPHinXsys users. The new one getInterParticleDiffusionCoff(particle_i, particle_i, Vecd::Zero()) is more clear that the diffusion coefficient in this process (diffusion body contacted with Dirichlet boundary) has nothing to do with the contact walls.
> 
> For the diffusion part, we just have done the diffusion body interacting with the wall boundaries. Later, we will do the diffusion process referring to the interaction between two diffusion bodies.

@ChenxiZhaoTUM So, now the diffusion process between two bodies can not be handled?
