### ISSUE TITLE
Unable to build in debug mode

### ISSUE THREAD

**Issue by ngkhaiching2000** [Xiangyu-Hu/SPHinXsys#39]
Hi Prof:

By referring to my previous question:
--------------------------------------------
I've tried to build the same project in "Debug" mode as well; unfortunately I am getting the error like this:
C1128 number of sections exceeded object file format limit: compile with /bigobj sphinxsys_static_2d C:\Research\SPHinXsys-master\SPHINXsys\src\for_2D_build\geometries\geometry.cpp

C1128 number of sections exceeded object file format limit: compile with /bigobj sphinxsys_2d
C:\Research\SPHinXsys-master\SPHINXsys\src\for_2D_build\geometries\geometry.cpp

LNK1104 cannot open file '......\SPHINXsys\lib\Debug\sphinxsys_2d.lib' test_2d_poiseuille_flow
Link

I've changed the cmake_build_type in cmake to "Debug" as well, same errors are obtained.

My solution:
-------------
I have regenerated the solution file using cmake and set CMAKE_Build_type = RelWithDebInfo.
Then, I opened the project using VS2017 and build using RelWithDebInfo.

It works with no error.

I guess we have to navigate back to "cmake" to change the build type & generate the solution file again whenever 
we want to switch between release & debug mode in VS ?

**Comment by Xiangyu-Hu** [comment]
Yes. This is the case. I will add your comments into the Readme file.
