### ISSUE TITLE
Artifact also for vcpkg

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#416]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/0c06b8c2560ade21990496a035bb7dc5c71743e3/.github/workflows/ci.yml#L150-L151
Could we also zip the vcpkg folder?

**Comment by FabienPean-Virtonomy** [comment]
Possible but for what purpose? The vcpkg binaries are already cached:
https://github.com/Xiangyu-Hu/SPHinXsys/blob/e1f6a08b20bdea6fddeebca49c138f82816ee814/.github/workflows/ci.yml#L114

**Comment by Xiangyu-Hu** [comment]
OK. Cache is sufficient.
