### ISSUE TITLE
General Continuum Consittue relation?

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#435]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/b811e7571851c8d754f06ac163b4f03d9297bccf/tests/user_examples/extra_src/shared/general_continuum/general_continuum.cpp#L20-L28
Seems not in agree with the manuscript? What is the stress here for? update the rotation term?
@Shuaihao-Zhang

**Comment by Shuaihao-Zhang** [comment]
This constitutive relation is for the nested formulation. 

The Cauchy stress rate is calculated with `Matd stress_rate = 2.0 * G_ * deviatoric_strain_rate;`

We used the Jaumann stress rate (i.e., object stress rate) here to remove the rigid body rotation.
https://github.com/Xiangyu-Hu/SPHinXsys/blob/b811e7571851c8d754f06ac163b4f03d9297bccf/tests/user_examples/extra_src/shared/general_continuum/general_continuum.cpp#L26

The last two item `shear_stress * (spin_rate.transpose()) + spin_rate * shear_stress` is to exclude the rigid body rotation. 

In the manuscript, I just illustrated the formulation of Cauchy stress tensor for the nested formulation.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/43480b6b-ac5f-4ad9-afec-607109b773ca)

For all the cases, I used the Jaumann stress rate.

Maybe I can add this part to the manuscript later. But anyway, the nested formulation is not our focus here, and the reference paper about the nested formulation (such as Gray's paper) all talked about this. And also, the results are the same if we use this Jaumann stress rate or not.

**Comment by Xiangyu-Hu** [comment]
Yes. I think that we can put the rigid rotation later in the manuscript.

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang However, this term may be important for plastic case. 
For example, if we consider pure plastic, the correction force magnitude should be the same, 
but it should rotate with rotation.

**Comment by Shuaihao-Zhang** [comment]
> @Shuaihao-Zhang However, this term may be important for plastic case. For example, if we consider pure plastic, the correction force magnitude should be the same, but it should rotate with rotation.

These two items "shear_stress * (spin_rate.transpose()) + spin_rate * shear_stress" also don't have much impact for the result when modelling plastic materials like soils. Maybe they are important for the correction term in the hourglass control.
