### ISSUE TITLE
Repeat computing stress tensor

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#437]
It seems a bug to compute stress increment twice?

https://github.com/Xiangyu-Hu/SPHinXsys/blob/d0ca341e79fee525e2a66d7353956ec7a1a154c4/tests/user_examples/extra_src/shared/general_continuum/continuum_dynamics/continuum_dynamics_inner.hpp#L42-L43

**Comment by Shuaihao-Zhang** [comment]
Here, the first line is to update the stress tensor, and the second line is to update the strain tensor.

**Comment by Xiangyu-Hu** [comment]
Ok. The two lines looks almost the the same and make apparent confusion.
