### ISSUE TITLE
Confusion comments

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#438]
Here the comments are confusion:

https://github.com/Xiangyu-Hu/SPHinXsys/blob/d0ca341e79fee525e2a66d7353956ec7a1a154c4/tests/user_examples/extra_src/shared/general_continuum/general_continuum.h#L48-L52

**Comment by Shuaihao-Zhang** [comment]
There are several parameters for Drucker Prager's elastoplastic model. Here, I employed this model to simulate soils.

**Comment by Xiangyu-Hu** [comment]
I mean that the comments here are quite confusing.

**Comment by Shuaihao-Zhang** [comment]
This is the reference paper. I will update this part later.

[Num Anal Meth Geomechanics - 2008 - Bui.pdf](https://github.com/Xiangyu-Hu/SPHinXsys/files/12665801/Num.Anal.Meth.Geomechanics.-.2008.-.Bui.pdf)

**Comment by Xiangyu-Hu** [comment]
the file is out of date.
