### ISSUE TITLE
A problem about the test example:test_2d_wetting_effects

### ISSUE THREAD

**Issue by HXJ111111** [Xiangyu-Hu/SPHinXsys#440]
There seemed to be a problem with test_2d_wetting_effects: when I ran the original code for the example, everything was fine, and the square droplets were able to evolve stable contact angles(150°）.
![angle](https://github.com/Xiangyu-Hu/SPHinXsys/assets/142018752/3715ac03-e386-473e-a82c-0524e2f05e87)

But once I added gravity to the wetting.cpp file, the square drops just collapsed.
![collapse](https://github.com/Xiangyu-Hu/SPHinXsys/assets/142018752/ef82a2ac-9b99-4943-b103-cf8f6481bdf0)

The only change I made to the code was the addition of gravity, even if the gravity is very small (0.0098), the droplet will still collapse.
![change](https://github.com/Xiangyu-Hu/SPHinXsys/assets/142018752/d68e3fdf-83cd-4c50-a5e0-9c7bfbcd9406)

I made some attempts to solve the problem, but it didn't work out. I would like to know how to deal with this problem.

**Comment by ChiZhangatTUM** [comment]
In this case,  no external body forces apply (i.e., no grav-ity) and surface tension is dominating the system. See Ref. https://doi.org/10.1016/j.jcp.2013.02.038

**Comment by HXJ111111** [comment]
> In this case, no external body forces apply (i.e., no grav-ity) and surface tension is dominating the system. See Ref. [https://doi.org/10.1016/j.jcp.2013.02.038[ ](https://sci-hub.se/10.1016/j.jcp.2013.02.038)](https://doi.org/10.1016/j.jcp.2013.02.038)

Thanks for your reply!
If I need to apply external force to a droplet, are there some similar examples in SPHinXsys, or  references that can help me?
I would be very grateful if you could give me some suggestions！

**Comment by ChiZhangatTUM** [comment]
> > In this case, no external body forces apply (i.e., no grav-ity) and surface tension is dominating the system. See Ref. [https://doi.org/10.1016/j.jcp.2013.02.038[ ](https://sci-hub.se/10.1016/j.jcp.2013.02.038)](https://doi.org/10.1016/j.jcp.2013.02.038)
> 
> Thanks for your reply! If I need to apply external force to a droplet, are there some similar examples in SPHinXsys, or references that can help me? I would be very grateful if you could give me some suggestions！

Then, you should find a reference, adjust all the parameters properly, not only add the gravity.

**Comment by HXJ111111** [comment]
> > > In this case, no external body forces apply (i.e., no grav-ity) and surface tension is dominating the system. See Ref. [https://doi.org/10.1016/j.jcp.2013.02.038[ ](https://sci-hub.se/10.1016/j.jcp.2013.02.038)]([https://doi.org/10.1016/j.jcp.2013.02.038[  ](https://sci-hub.se/10.1016/j.jcp.2013.02.038)](https://doi.org/10.1016/j.jcp.2013.02.038))
> > 
> > 
> > Thanks for your reply! If I need to apply external force to a droplet, are there some similar examples in SPHinXsys, or references that can help me? I would be very grateful if you could give me some suggestions！
> 
> Then, you should find a reference, adjust all the parameters properly, not only add the gravity.

Ok, I will try it according to your suggestion, thank you very much!
