### ISSUE TITLE
MacOs test or build fails due to  install dependencies.

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#472]
Installing 93/106 fontconfig:x64-osx...
Building fontconfig[core]:x64-osx...
-- Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.2/fontconfig-2.14.2.tar.gz -> fontconfig-fontconfig-2.14.2.tar.gz...
-- Extracting source /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/downloads/fontconfig-fontconfig-2.14.2.tar.gz
-- Applying patch no-etc-symlinks.patch
-- Applying patch libgetopt.patch
-- Applying patch fix-preprocessor-clang-cl.patch
-- Using source at /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/src/2.14.2-7f52ee670b.clean
-- Found external ninja('1.11.1').
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/local/bin/python3 /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/installed/x64-osx/tools/meson/meson.py -Ddoc=disabled -Dcache-build=disabled -Dtests=disabled --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/meson-x64-osx-dbg.log -Ddebug=true --prefix /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/packages/fontconfig_x64-osx/debug --includedir ../include -Dcmake_prefix_path=['/Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/installed/x64-osx/debug','/Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/installed/x64-osx'] /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/src/2.14.2-7f52ee670b.clean
    Working Directory: /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/config-x64-osx-dbg-meson-log.txt.log
      /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/config-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:431 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:16 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

error: building fontconfig:x64-osx failed with: BUILD_FAILED

**Comment by junwei-jiang** [comment]
It seems like there was an error while building the fontconfig library for the x64-osx target using vcpkg.

maybe you can see the log files:
/Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/config-x64-osx-dbg-meson-log.txt.log
/Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/config-x64-osx-dbg-out.log

And check if the python version being used is compatible with the build process. [Someone](https://github.com/microsoft/vcpkg/issues/25035) solved this problem by update python(but im not sure if the problem is same)

And it seems that [this person](https://github.com/microsoft/vcpkg/issues/31700) encountered the exact same problem as you (Call Stack), but he was on Linux, maybe you can refer to it.

I don't have a Mac so I can't reproduce the problem, I hope this helps. Or can report an issue [here](https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+in%3Atitle+fontconfig+)

**Comment by Xiangyu-Hu** [comment]
It seems that in the reference, the python3 version is too. However, the macOS Github runner is using python3 3.12.0, much higher than 3.7.

**Comment by Xiangyu-Hu** [comment]
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

**Comment by FabienPean-Virtonomy** [comment]
If anyone uses a mac, reproducing the error and posting the logs would be most helpful:
> /Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/config-x64-osx-dbg-meson-log.txt.log
/Users/runner/work/SPHinXsys/SPHinXsys/vcpkg/buildtrees/fontconfig/config-x64-osx-dbg-out.log

**Comment by ChiZhangatTUM** [comment]
Did not find a solution, will continue.

**Comment by Xiangyu-Hu** [comment]
> Did not find a solution, will continue.

What is the exact error message on MacOs?

**Comment by ChiZhangatTUM** [comment]
Seem that fontconfig installation works fine for latest vcpkg (git pull, ./vcpkg upgrade) on my MAC OS 13.6.1

-- Extracting source /Users/chizhang/Prefix/vcpkg/downloads/fontconfig-fontconfig-2.14.2.tar.gz
-- Applying patch no-etc-symlinks.patch
-- Applying patch libgetopt.patch
-- Applying patch fix-preprocessor-clang-cl.patch
-- Using source at /Users/chizhang/Prefix/vcpkg/buildtrees/fontconfig/src/2.14.2-7f52ee670b.clean
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Configuring x64-osx-dbg
-- Configuring x64-osx-dbg done
-- Configuring x64-osx-rel
-- Configuring x64-osx-rel done
-- Package x64-osx-dbg
-- Package x64-osx-rel
-- Fixing pkgconfig file: /Users/chizhang/Prefix/vcpkg/packages/fontconfig_x64-osx/lib/pkgconfig/fontconfig.pc
-- Fixing pkgconfig file: /Users/chizhang/Prefix/vcpkg/packages/fontconfig_x64-osx/debug/lib/pkgconfig/fontconfig.pc
-- Installing: /Users/chizhang/Prefix/vcpkg/packages/fontconfig_x64-osx/share/fontconfig/usage
-- Installing: /Users/chizhang/Prefix/vcpkg/packages/fontconfig_x64-osx/share/fontconfig/copyright
-- Performing post-build validation
-- Performing post-build validation done

**Comment by Xiangyu-Hu** [comment]
Could SPHinXsys install on the system? If it is the case, we can update the version of VCPKG.

**Comment by ChiZhangatTUM** [comment]
> Could SPHinXsys install on the system? If it is the case, we can update the version of VCPKG.

I have another issue with open cascade installation using updated vcpkg. 
With open cascade, vcpkg can not upgrade, therefore, I first try to updated vckpage then solve this issue.

**Comment by ChiZhangatTUM** [comment]
Error:
chizhang@chideMBP vcpkg % ./vcpkg install opencascade
Computing installation plan...
error: Unrecognized identifer name xbox. Add to override list in triplet file.
opencascade[core]:x64-osx is only supported on '!(uwp | xbox | osx | arm)'

**Comment by ChiZhangatTUM** [comment]
Other dependency works fin:

   openblas:x64-osx: SUCCEEDED: 3.724 min
    blas:x64-osx: SUCCEEDED: 3.162 s
    boost-uninstall:x64-osx: SUCCEEDED: 66.57 ms
    boost-vcpkg-helpers:x64-osx: SUCCEEDED: 174.5 ms
    boost-config:x64-osx: SUCCEEDED: 1.59 s
    boost-assert:x64-osx: SUCCEEDED: 611.8 ms
    boost-static-assert:x64-osx: SUCCEEDED: 605.8 ms
    boost-throw-exception:x64-osx: SUCCEEDED: 836.5 ms
    boost-core:x64-osx: SUCCEEDED: 806.7 ms
    boost-align:x64-osx: SUCCEEDED: 783 ms
    boost-mp11:x64-osx: SUCCEEDED: 549 ms
    boost-describe:x64-osx: SUCCEEDED: 557.7 ms
    boost-type-traits:x64-osx: SUCCEEDED: 1.2 s
    boost-container-hash:x64-osx: SUCCEEDED: 785.3 ms
    boost-preprocessor:x64-osx: SUCCEEDED: 1.916 s
    boost-type-index:x64-osx: SUCCEEDED: 693.6 ms
    boost-any:x64-osx: SUCCEEDED: 658.2 ms
    boost-array:x64-osx: SUCCEEDED: 634.8 ms
    boost-bind:x64-osx: SUCCEEDED: 753.2 ms
    boost-concept-check:x64-osx: SUCCEEDED: 726.6 ms
    boost-move:x64-osx: SUCCEEDED: 739.9 ms
    boost-smart-ptr:x64-osx: SUCCEEDED: 1.116 s
    boost-typeof:x64-osx: SUCCEEDED: 817.3 ms
    boost-conversion:x64-osx: SUCCEEDED: 652.7 ms
    boost-detail:x64-osx: SUCCEEDED: 891.9 ms
    boost-integer:x64-osx: SUCCEEDED: 738.7 ms
    boost-dynamic-bitset:x64-osx: SUCCEEDED: 629.6 ms
    boost-endian:x64-osx: SUCCEEDED: 880 ms
    boost-function:x64-osx: SUCCEEDED: 804.1 ms
    boost-predef:x64-osx: SUCCEEDED: 972.7 ms
    boost-io:x64-osx: SUCCEEDED: 617.2 ms
    boost-utility:x64-osx: SUCCEEDED: 907.8 ms
    boost-mpl:x64-osx: SUCCEEDED: 3.085 s
    boost-function-types:x64-osx: SUCCEEDED: 999.8 ms
    boost-functional:x64-osx: SUCCEEDED: 684.9 ms
    boost-tuple:x64-osx: SUCCEEDED: 777.3 ms
    boost-fusion:x64-osx: SUCCEEDED: 3.124 s
    boost-intrusive:x64-osx: SUCCEEDED: 1.074 s
    boost-optional:x64-osx: SUCCEEDED: 855.5 ms
    boost-iterator:x64-osx: SUCCEEDED: 1.142 s
    boost-modular-build-helper:x64-osx: SUCCEEDED: 97.99 ms
    boost-numeric-conversion:x64-osx: SUCCEEDED: 1.789 s
    boost-polygon:x64-osx: SUCCEEDED: 1.838 s
    boost-winapi:x64-osx: SUCCEEDED: 776 ms
    boost-pool:x64-osx: SUCCEEDED: 944.6 ms
    boost-qvm:x64-osx: SUCCEEDED: 1.1 s
    boost-rational:x64-osx: SUCCEEDED: 725.1 ms
    boost-ratio:x64-osx: SUCCEEDED: 779.4 ms
    boost-tokenizer:x64-osx: SUCCEEDED: 688 ms
    boost-unordered:x64-osx: SUCCEEDED: 1.674 s
    boost-variant:x64-osx: SUCCEEDED: 871.5 ms
    boost-variant2:x64-osx: SUCCEEDED: 802.8 ms
    brotli:x64-osx: SUCCEEDED: 13.86 s
    bzip2:x64-osx: SUCCEEDED: 8.114 s
    dirent:x64-osx: SUCCEEDED: 66.06 ms
    zlib:x64-osx: SUCCEEDED: 5.367 s
    libpng:x64-osx: SUCCEEDED: 6.833 s
    freetype:x64-osx: SUCCEEDED: 14.11 s
    gettext:x64-osx: SUCCEEDED: 8.918 s
    gperf:x64-osx: SUCCEEDED: 4.986 s
    fontconfig:x64-osx: SUCCEEDED: 37.59 s
    gtest:x64-osx: SUCCEEDED: 19.19 s
    lapack-reference:x64-osx: SUCCEEDED: 6.388 min
    lapack:x64-osx: SUCCEEDED: 4.178 s
    simbody:x64-osx: SUCCEEDED: 6.777 min

**Comment by FabienPean-Virtonomy** [comment]
opencascade is not supported on osx according to vcpkg manifest file, how was it even passing before ?

> error: Unrecognized identifer name xbox. Add to override list in triplet file.

After you pulled, you likely need to bootstrap the executable again.

**Comment by ChiZhangatTUM** [comment]
> > error: Unrecognized identifer name xbox. Add to override list in triplet file.
> 
> After you pulled, you likely need to bootstrap the executable again.
> 
> opencascade is not supported on osx according to vcpkg manifest file, how was it even passing before ?
> 
> EDIT: Ok that's why, it was forced with `--allow-unsupported`.
> 
> https://github.com/Xiangyu-Hu/SPHinXsys/blob/d85a5e6683947acd1d7964a636a6bcb1bd6b79d4/.github/workflows/ci.yml#L430-L439

Yes, I forgot this.

**Comment by ChiZhangatTUM** [comment]
Seems an upstream issue.
