### ISSUE TITLE
The bug when Register a shared variable in the base part without a signal, and the bug in the test case: multiresotion flow around cylinder

### ISSUE THREAD

**Issue by FengWang3119** [Xiangyu-Hu/SPHinXsys#485]
1. When Register a shared variable in the base part without a signal &, the inherited clase that also uses this variable has trouble. 
To be more specific, when use the emiiter function, the size of the variable that is used in the inherited classs is not updated.

2. And in the test case: multiresotion flow around cylinder, the velocity at the interface between high and low resolution seems to have Intermittent

**Comment by Xiangyu-Hu** [comment]
The error is due to registering a shared variable without using reference.
