### ISSUE TITLE
Function in solid particles never used?

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#487]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/dce21a0ae44c03a8fce7ef02e70848861054a958/src/shared/particles/solid_particles.h#L98-L131

I am wondering whether these function are used or not. If not, it is better to delete them.

**Comment by BenceVirtonomy** [comment]
If they are not used, please remove them. Post-processing should not be inside this class in my opinion but completely separated.

**Comment by Xiangyu-Hu** [comment]
They are deleted now.
