### ISSUE TITLE
2d wave elastic wall not able restart

### ISSUE THREAD

**Issue by spadaxsys-dev** [Xiangyu-Hu/SPHinXsys#5]
This is because the functions
	void SolidParticles::WriteParticlesToXmlForRestart(std::string &filefullpath)
and 
	void SolidParticles::ReadParticleFromXmlForRestart(std::string &filefullpath)
not written correctly.

**Comment by ccyx** [comment]
I find test_2d_fsi2 case also not able restart, because this issue.

**Comment by Xiangyu-Hu** [comment]
Thanks for the comment. We can check it this week. However, it seems that only small modifications are required for this. I can merge your modifications if you can make it done.
