### ISSUE TITLE
latest master cannot compile through

### ISSUE THREAD

**Issue by alundilong** [Xiangyu-Hu/SPHinXsys#52]
Old master works fine (around 5-7 days back, cannot remember exactly).
For current master, visual studio 2017 (windows 10) reports a numerous errors related to xstring, stdexcept, xlocinfo...., etc. Please see the attached.

I would like to checkout a new branch to work on a new feature, but I cannot move on. 

![image](https://user-images.githubusercontent.com/24465615/129667956-028b2480-a6f7-4789-ac50-4ce5987dd662.png)

**Comment by Xiangyu-Hu** [comment]
I have just do compile the in in MSVC 2019, it works. There are two test cases not compile in windows due to google test setup in cmake files. Other cases and the library are all ok.

**Comment by alundilong** [comment]
> May be a issue to Cmake? Did you rerun the Cmake with deleting cache?

Yes. I see the same problem. Two test cases failed compiling due to googletest setup. The error in CMake lead VS's failure in locating gtest.lib.

**Comment by alundilong** [comment]
> > May be a issue to Cmake? Did you rerun the Cmake with deleting cache?
> 
> Yes. I see the same problem. Two test cases failed compiling due to googletest setup. The error in CMake lead VS's failure in locating gtest.lib.

**Comment by alundilong** [comment]
> I have just do compile the in in MSVC 2019, it works. There are two test cases not compile in windows due to google test setup in cmake files. Other cases and the library are all ok.

I'll try MSVC 2019 out later. Thanks.

**Comment by alundilong** [comment]
Now I find files, such as c_exp.c, c_cos.c, at SPHINXsys/src/shared/clapack_for_SPHinXsys/F2CLIBS/libf2c/ are causing problems.

<img width="837" alt="lALPD4PvN-97y4HNA5LNBok_1673_914" src="https://user-images.githubusercontent.com/24465615/130032492-c411a308-da9b-4783-8f7d-bfa3cf2567a6.png">

**Comment by alundilong** [comment]
Remove files at SPHINXsys\src\shared\clapack_for_SPHinXsys and \SPHINXsys\src\shared\simbody, compile was successful except for two test cases which need a manual setting of add gtest.lib through visual studio.

**Comment by alundilong** [comment]
My git-clone seems downloaded all submodules which should be ignored. This is root causing the failure. Now the alarm is cleared. Thank you for attention. @Xiangyu-Hu
