### ISSUE TITLE
Is it possible to create the emitter by using shape?

### ISSUE THREAD

**Issue by FengWang3119** [Xiangyu-Hu/SPHinXsys#550]
Generally, we create emitter by using emitter_translation and emitter_halfsize, as shown in picture.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/118197034/646c67f3-ecb2-4c74-a153-2f9a6f4a53ef)
But, is it possible to construct this emitter by importing a multipolygon that consists of some points ?
I need to extrude the emitter but currently I could't find the interface to designate the shape without using translation and halfsize

**Comment by Xiangyu-Hu** [comment]
Now, the emitter must be a aligned box.
