### ISSUE TITLE
Details on broken CI

### ISSUE THREAD

**Issue by FabienPean-Virtonomy** [Xiangyu-Hu/SPHinXsys#563]
@Xiangyu-Hu The cause has been identified. It is an issue with vcpkg with CMake 3.29.1. It will fix itself in coming days (1) as soon as vcpkg upgrade the CMake baseline and (2) the weekly runner images are regenerated. 

https://github.com/actions/runner-images/issues/9680
https://github.com/microsoft/vcpkg/issues/37968
https://github.com/microsoft/vcpkg/pull/38144

It is possible to pin the CMake version in the future by (1) forcing vcpkg to use system binaries, and (2) deleting runner image embedded CMake executable which is called before the system installed version (because of Path order), at least on Ubuntu. To be determined for MacOS and Windows

**Comment by Xiangyu-Hu** [comment]
Thanks. We first wait if the fix will updated.

**Comment by Xiangyu-Hu** [comment]
Still need wait some time.

**Comment by Xiangyu-Hu** [comment]
It seems that vcpkg is OK now.
