### ISSUE TITLE
delete functions in solid particle

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#569]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/ea091def9749e736b798016efd994b1f8898e2d1/src/shared/particles/solid_particles.h#L90-L131

In order to achieve separation between particle class from physical method classes, I am going to clean all particles so that at last only base particles left.  For this, I need to clean all functions in particles classes.

@BenceVirtonomy @FabienPean-Virtonomy  Could you help to move these functions out, or I can delete if they are not useful anymore?

**Comment by FabienPean-Virtonomy** [comment]
> In order to achieve separation between particle class from physical method classes, I am going to clean all particles so that at last only base particles left. For this, I need to clean all functions in particles classes.

I agree that they should be free functions, they can be cut out of the `ElasticSOlidParticles` class

**Comment by Xiangyu-Hu** [comment]
This is done in #582.
