### ISSUE TITLE
Kernel function for beam?

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#570]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/ea091def9749e736b798016efd994b1f8898e2d1/src/for_3D_build/particles/beam_particles.cpp#L22
It seems that beam dynamics still using shell kernel function?

@rukawaaaaaaa Could you have a check? Thanks.

**Comment by rukawaaaaaaa** [comment]
I use another reduceOnce() which is in the line 57 of test_3d_slender_beam.cpp.

**Comment by rukawaaaaaaa** [comment]
> https://github.com/Xiangyu-Hu/SPHinXsys/blob/ea091def9749e736b798016efd994b1f8898e2d1/src/for_3D_build/particles/beam_particles.cpp#L22
> 
> 
> It seems that beam dynamics still using shell kernel function?
> @rukawaaaaaaa Could you have a check? Thanks.


I use another reduceOnce() which is in the line 57 of test_3d_slender_beam.cpp.

**Comment by Xiangyu-Hu** [comment]
Ok.
