### ISSUE TITLE
Reload File leads to assert failure when use debug mode in Vscode

### ISSUE THREAD

**Issue by FengWang3119** [Xiangyu-Hu/SPHinXsys#574]
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/118197034/952c505b-992a-4b39-927c-154f4b7417a7)
I run the test case: 2d standing wave with debug mode in vscode, when I input relaxed fluid particle data, the assertation fails. 
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/118197034/30ce3933-fb91-4a4e-8b8e-55240cb6788e)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/118197034/3f81273b-7e18-4407-b350-4d15458cfe53)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/118197034/b65e8c3e-90c6-4fc0-96ad-82dd6cc6d1b7)
When I use the release mode or release with debug information mode, this case is OK, since in these 2 modes, assertation seems not function. 
This situation also happens in my own case when I want to reload data with debug mode.

**Comment by Xiangyu-Hu** [comment]
Has the problem solved with the nearest bug fix pull request #575?
