### ISSUE TITLE
Seems a serious bug

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#580]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/230f9a1bc08097a265bfe65873c20f436a7e28eb/tests/optimization/test_2d_VP_heat_flux_optimization/VP_heat_flux_optimization.cpp#L383

This line code seems not able copy data seems both variables are references of a large vector.

**Comment by Bo-Zhang1995** [comment]
I suppose I will change it into an interface function. Then, I will pull request.

**Comment by Xiangyu-Hu** [comment]
> I suppose I will change it into an interface function. Then, I will pull request.

I have actually changed them in the latest pull request now in review. Please have a check.
