### ISSUE TITLE
Seems heat conductivity never used

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#581]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/fa14df82e0d4d99df7e1737072d71a8465f31c51/tests/2d_examples/test_2d_windows_frame_diffusion_D4/windows_frame_diffusion_D4.h#L27-L28

It seems that these two variable are never used.

**Comment by Xiangyu-Hu** [comment]
@DongWuTUM  @Bo-Zhang1995 Could you check with Haotian?

**Comment by DongWuTUM** [comment]
> @DongWuTUM @Bo-Zhang1995 Could you check with Haotian @Harmon9802 ?

I have told Haotian. He will check it.

**Comment by Harmon9802** [comment]
> @DongWuTUM @Bo-Zhang1995 Could you check with Haotian @Harmon9802 ?

epdm_cond and pane_cond are used for thermal conductivity initialization, and epdm are also used to define the time step as it is the largest conductivity in this case.
![1](https://github.com/Xiangyu-Hu/SPHinXsys/assets/120639809/61d11315-619e-472c-9d83-0ce2b1b4a0b7)
![2](https://github.com/Xiangyu-Hu/SPHinXsys/assets/120639809/3047e821-7890-492a-93d4-069fd73df263)

**Comment by Xiangyu-Hu** [comment]
Understood. The current material model seems lack of mechanism of putting these diffusivities into the diffusive material directly.
