### ISSUE TITLE
pull request #548 leads to compile failure for windows.

### ISSUE THREAD

**Issue by Bo-Zhang1995** [Xiangyu-Hu/SPHinXsys#585]
Today, I wanted to merge my code and try the latest master, but I could not compile it with errors.
I checked the different code versions and found that pull request #548  leads to this problem.
Actually, the errors are the same as the ones reported by Dong at the group meeting.
I suppose this is a bug for the Windows compile.

The error is located at https://github.com/Xiangyu-Hu/SPHinXsys/blob/1f2f4668447dcc04cdc7cb054950426b7cf61cf1/src/shared/particle_dynamics/particle_dynamics_algorithms.h#L135.
The errors are shown below.
![微信图片_20240608190238](https://github.com/Xiangyu-Hu/SPHinXsys/assets/57928811/c01405a8-c5f2-4294-9487-18f34b2ebaa0)

**Comment by Bo-Zhang1995** [comment]
https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/9416215938/job/25938830240?pr=584#step:9:89
Here is the error in Dong's pull request. They are the same. @DongWuTUM

**Comment by Bo-Zhang1995** [comment]
It seems that this line 
https://github.com/Xiangyu-Hu/SPHinXsys/blob/1f2f4668447dcc04cdc7cb054950426b7cf61cf1/src/shared/particle_dynamics/particle_dynamics_algorithms.h#L138 should be put before the public function, as far as I have tested, it works currently.

**Comment by Xiangyu-Hu** [comment]
This is corrected in #588 pull request.
