### ISSUE TITLE
position_based_boundary_conditions cannot pass at CI stage

### ISSUE THREAD

**Issue by alundilong** [Xiangyu-Hu/SPHinXsys#59]
this test case has successfully passed on my own laptop, yet not working at CI stage on github. 
On my laptop,
![448e82e930f61dd7966cda2005d0ddd](https://user-images.githubusercontent.com/24465615/132644722-c82e5bec-289f-4215-b8e1-8023b0c26b57.png)

CI,
![9a7ed75fa853f28eee222059f2006e5](https://user-images.githubusercontent.com/24465615/132644794-800d9938-c79a-4eff-a427-e08d551e5f11.png)

**Comment by alundilong** [comment]
I did another test on my laptop, still it passed with no complain at all.
![1631179961](https://user-images.githubusercontent.com/24465615/132661463-e13bd768-816a-4979-91c4-9d73e6360d75.png)

**Comment by BenceVirtonomy** [comment]
you can remove this test, it will be removed in my new pull request

**Comment by alundilong** [comment]
My last pull request was a success, so I did not remove this test case @BenceVirtonomy
