### ISSUE TITLE
ULSPH--Hourglass control--Limiter

### ISSUE THREAD

**Issue by Shuaihao-Zhang** [Xiangyu-Hu/SPHinXsys#598]
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/98051750-4433-4657-8803-f4818d5abc87)
The two types of limiter don't work, and the result still suffer from hourglass issue.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/c4d809a6-8609-4a06-b4c1-21123a99d513)
I think there is an inconsistency in the limiter, i.e.,
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/161a70d6-53a4-4b77-9297-c244b7a65e33)
So, the denominator should be `u_ij` rather that `r_ij`, i.e.,
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/4f66f1bd-3b8d-43e9-b5ab-79ee4bfaa80b)
The final form of the limiter should be:
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/63bbeb31-39e0-4ea5-85b0-85c4bef046c3)
This works good for 2D oscillating beam.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/13f35226-6fda-4dce-b071-1925b18c4745)

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang your idea is reasonable.

**Comment by Shuaihao-Zhang** [comment]
@Xiangyu-Hu  Thanks.
Another thing is that I would like to discuss about whether the limiter is necessary or not.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/07a37ef8-616a-4918-993d-620dd3ef85a9)
For the 2D oscillating beam, it seems that the limiter doesn't have much effect for the results, no matter for the convergence and accuracy.
For the 3D bending column, the hourglass can be remove no matter with or without the limiter, 
While for the displacement of the observation point, they are quite different.
The result  with limiter:
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/7ea181f3-f6a8-4f00-8b67-060c94ba187a)
The result without limiter
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/7e0b587d-ab8a-4d28-b856-5a1d8ad2494d)
It can be seen that, although both of them show good convergence, the result without limiter is closer to the FVM result when with the same resolution.
The results of ULSPH without a limiter are also closer to the results of Dong's TLSPH method.
Here is Dong's TLSPH result;
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/3c5f2c29-4f90-4c70-8d09-6a7cd742ad31)

So, I wonder whether the limiter is necessary, or maybe we still need to modify the current form of limiter.

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang what do you mean without limiter? what is the parameter used when not using limiter?

**Comment by Shuaihao-Zhang** [comment]
@Xiangyu-Hu Here are the equations with and without limiter:
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/af478c40-7123-48f7-a93a-944d08d6dec8)

**Comment by DongWuTUM** [comment]
> @Xiangyu-Hu Here are the equations with and without limiter: ![image](https://private-user-images.githubusercontent.com/43446342/340307335-af478c40-7123-48f7-a93a-944d08d6dec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzMwNzUsIm5iZiI6MTcxODYzMjc3NSwicGF0aCI6Ii80MzQ0NjM0Mi8zNDAzMDczMzUtYWY0NzhjNDAtNzEyMy00OGY3LWE5M2EtOTQ0ZDA4ZDZkZWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEzNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MTUzMzYxMWMzNDljYWQyN2M4ZGM2NzEyMGQzYTVhZGIyNGI4ZTNkYjQzYzIzMDE5OWU1NmVjNjllMmVjNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wj-55UkXx8I-MMYnQdsjZ9HVYaqge9yVjgiHtftnXoc)

You can try to adjust the parameters in the limiter. And what is the valve of $\xi$.

**Comment by Xiangyu-Hu** [comment]
> @Xiangyu-Hu Here are the equations with and without limiter:
> ![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/af478c40-7123-48f7-a93a-944d08d6dec8)
> 

I think that would be a bit strange as the   limiter decreases the correction which should mean better solution.

**Comment by Shuaihao-Zhang** [comment]
@DongWuTUM The $\xi$ is fixed to 4.
If I remove the 0.05 in the limiter, and change the coefficient in the limiter to 100, the result is much better.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/7e1a292f-97d9-45c7-93c5-c7022e0471c0)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/496dadd0-df4f-4963-baa3-ea8df53560a7)
So, do you think the above form of limiter is acceptable @Xiangyu-Hu @DongWuTUM

**Comment by Shuaihao-Zhang** [comment]
> > @Xiangyu-Hu Here are the equations with and without limiter:
> > ![image](https://private-user-images.githubusercontent.com/43446342/340307335-af478c40-7123-48f7-a93a-944d08d6dec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDEyMDUsIm5iZiI6MTcxODY0MDkwNSwicGF0aCI6Ii80MzQ0NjM0Mi8zNDAzMDczMzUtYWY0NzhjNDAtNzEyMy00OGY3LWE5M2EtOTQ0ZDA4ZDZkZWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE2MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NzFjZjIyOGU2MGMyYzRiNDRjZjM1MjZhODk0YmU2ODQ0MTI0Njk4ZGVhYzc2NDI4NmVjZTM4NmQwMzIxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wm7SSoxHJQgNYrE7S_HbGHQn7jryobYjw_Rre-682Rg)
> 
> I think that would be a bit strange as the limiter decreases the correction which should mean better solution.

Maybe we can explain the result in this way.
The correction term is smaller when with limiter, which means the shear force is smaller.
And as we now, the shear force acts as a resistance to the movement.
So, when with the limiter, shear force is smaller, which leads to larger displacement.

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang No. It is the correction is less should mean higher accuracy as the correction destroies accuracy.

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang No. Do you see that if you set xi to 4 and without limiter all cases are numerically stable?

**Comment by Shuaihao-Zhang** [comment]
> @Shuaihao-Zhang No. Do you see that if you set xi to 4 and without limiter all cases are numerically stable?

@Xiangyu-Hu Yes, all the simulations are stable when without limiter and $\xi$=4.

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang Now we compare
two simulations with and without limiter at a given resolution. We you post two pictures particles and stress profiles on one case? Say the bending case.

**Comment by Shuaihao-Zhang** [comment]
@Xiangyu-Hu  Sure, here it is.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/cf9a0ce8-27a3-483a-8a19-1994e40ad965)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/749f6483-7e59-4a83-85f3-043d912acef8)

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang it seems the results is ingreement with predictions. That is the limiter leads to more correction and hence less deformation, which generally suggests better solution.  However,  in this case, it seems that by accident,  the high resolution solution gives less deformation.  You can see with limiter the solution is second order convergence which suggests the property of the uncorrected formulation. If you do do not used limiter, it behaviors like first order. 
I think that you can check another case to see the behavior you have observed can be reproduced.

**Comment by Shuaihao-Zhang** [comment]
> @Shuaihao-Zhang it seems the results is ingreement with predictions. That is the limiter leads to more correction and hence less deformation, which generally suggests better solution. However, in this case, it seems that by accident, the high resolution solution gives less deformation. You can see with limiter the solution is second order convergence which suggests the property of the uncorrected formulation. If you do do not used limiter, it behaviors like first order. I think that you can check another case to see the behavior you have observed can be reproduced.

@Xiangyu-Hu 
(1) I think the limiter will lead to less correction and thus more deformation, since the limiter $\gamma<=1$。
This can be verified by the results.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/6376487b-3d21-4c4e-86f0-0a41b681bc0d)

(2) Yes, high resolution solution gives less deformation, which is the same with TLSPH result.
Below shows the TLSPH result for bending column.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/e87d5a10-a055-4f7d-b08f-88dc2c8ee676)

(3) Yes, when with limiter, the result seems like second-order convergence, otherwise, it seems like first-order convergence.
Below shows the results with and without limiter for 2D oscillating beam and 3D bending column.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/d8046bd2-cac1-4dee-89d0-f84f702ac0e1)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/5091c5de-c7ef-4169-adc5-206d19ce4af0)

**Comment by Xiangyu-Hu** [comment]
> > @Xiangyu-Hu Here are the equations with and without limiter:
> > ![image](https://private-user-images.githubusercontent.com/43446342/340307335-af478c40-7123-48f7-a93a-944d08d6dec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTc5MTMsIm5iZiI6MTcxODY5NzYxMywicGF0aCI6Ii80MzQ0NjM0Mi8zNDAzMDczMzUtYWY0NzhjNDAtNzEyMy00OGY3LWE5M2EtOTQ0ZDA4ZDZkZWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4MDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNWI1Y2EzNzY1MThmYjg3M2YwMWVmYWU0ZDMwZGU2MDgzN2I0Nzg4MzMxNjcwZmE4YmRkNThkZTNiZmUzMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h9OcgPm4mwUIqrBxioQCWs3lpGdo4-CITxHWf77AmiA)
> 
> I think that would be a bit strange as the limiter decreases the correction which should mean better solution.

@Shuaihao-Zhang Now, I am thinking that the correction actually may do not need the limiter if the correction term takes the role of supplementing the lost strain predicted from the standard formulation. Also if you cancel the x, as it is 4, with the 1/4 in front of the correction term, you have basically have the same factor as the first term. Therefore, may be simply combine xi and 1/4 together to 1 as final parameter. 

If you compare the first and the second term in

**Comment by Shuaihao-Zhang** [comment]
> > > @Xiangyu-Hu Here are the equations with and without limiter:
> > > ![image](https://private-user-images.githubusercontent.com/43446342/340307335-af478c40-7123-48f7-a93a-944d08d6dec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTc5MTMsIm5iZiI6MTcxODY5NzYxMywicGF0aCI6Ii80MzQ0NjM0Mi8zNDAzMDczMzUtYWY0NzhjNDAtNzEyMy00OGY3LWE5M2EtOTQ0ZDA4ZDZkZWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4MDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNWI1Y2EzNzY1MThmYjg3M2YwMWVmYWU0ZDMwZGU2MDgzN2I0Nzg4MzMxNjcwZmE4YmRkNThkZTNiZmUzMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h9OcgPm4mwUIqrBxioQCWs3lpGdo4-CITxHWf77AmiA)
> > 
> > 
> > I think that would be a bit strange as the limiter decreases the correction which should mean better solution.
> 
> @Shuaihao-Zhang Now, I am thinking that the correction actually may do not need the limiter if the correction term takes the role of supplementing the lost strain predicted from the standard formulation. Also if you cancel the x, as it is 4, with the 1/4 in front of the correction term, you have basically have the same factor as the first term. Therefore, may be simply combine xi and 1/4 together to 1 as final parameter.

Thanks! Then I will not use the limiter.

**Comment by Xiangyu-Hu** [comment]
We are settled now.
