### ISSUE TITLE
issue in CMakeLists.txt for two test cases in high_level_simulation_class directory

### ISSUE THREAD

**Issue by alundilong** [Xiangyu-Hu/SPHinXsys#60]
It seems only windows operating system is considered. Apparently, it was not intended. @

![image](https://user-images.githubusercontent.com/24465615/132670514-5e999603-59cb-4a3c-b969-ab3044eaf4fe.png)

Same issue for time_dependent_contact test

**Comment by alundilong** [comment]
Btw, gtest, gtest_main should be appended at line 46, otherwise, this test case cannot work.

**Comment by BenceVirtonomy** [comment]
Line 51 is Linux I think

**Comment by alundilong** [comment]
Thats right. I was misled by the wrong indentation.
