### ISSUE TITLE
Deviations in Simulation Outcomes for Long Channel Configurations from Analytical Results

### ISSUE THREAD

**Issue by YuVirtonomy** [Xiangyu-Hu/SPHinXsys#605]
### Description
When simulating fluid flow in long channel configurations, deviations in the velocity field from analytical results are observed. The simulation setup includes a parabolic velocity inlet with a maximum velocity of 1.0 and an outlet pressure set to 0. The Reynolds number (Re) is 100, with viscosity calculated accordingly. The resolution is set to DH/40. For the same setup, if DL = 10 DH, the results fit the analytical results very well.

### Simulation Setup
- **Inlet Velocity Profile:** Parabolic, maximum velocity = 1.0
- **Outlet Pressure:** 0
- **Reynolds Number (Re):** 100
- **Viscosity:** Calculated based on Re
- **Resolution:** DH/40
- **Simulation time:** 1000s
- **Boundary length:** 5* resolution_ref (no difference between using 3 * resolution_ref  and 5 * resolution_ref )
- **Function employed:** Integration1stHalfWithWallRiemann, Integration2ndHalfWithWallRiemann

### Observations
1. **Velocity Field:**
   - The velocity field deviates from the expected analytical results as the channel length increases.

    ![Velocity Field](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/29a0018e-dc53-407c-97e6-ca5bac7c211a)
    *Velocity field visualization*

2. **Pressure Field:**
   - The pressure field shows significant variations along the length of the channel instead of a steady pressure gradient toward the outlet.

    ![Pressure Field](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/a162152a-d352-449f-9e2f-ae6db8cb7e04)
    *Pressure field visualization*

3. **Velocity Profile at Mid-Channel:**
   - The velocity at the radial direction measured from X = DL*0.5 (where DL = DH * 50) shows deviations from the analytical profile.

    ![Velocity Profile](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/63c824b8-3efc-49c0-aeff-b5d80ce0ccaf)
    *Velocity at radial direction measured from X = 0.5DL*

   The velocity profile obtained from an observer at the last time step demonstrates that the maximum velocity is slower than the analytical result.

### Steps to Reproduce
Check out the branch: [issue/velocity_inlet](https://github.com/Xiangyu-Hu/SPHinXsys/tree/issue/velocity_inlet).

## Straight Channel Simulations
This section summarizes the results of simulations, focusing on various configurations within a straight channel each configuration details the parameters used, including domain length (DL), resolution, and corrections applied.

### Parameters and Configurations
Each simulation varied the domain length (`DL`), transport correction, linear correction, and resolution (`DH/40`), with Riemann solvers consistently applied. Observer in this section is located at 0.5DL.

#### **Simulations with DL = 10\*DH**
- **No Corrections**
  - ![No Corrections DL=10](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/c9d09a0b-b21a-4f19-83ed-1f016d7e8c24)
- **Linear Correction Only**
  - ![Linear Correction Only DL=10](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/363dbcb0-bdb7-4a72-ae0e-c741a2c2e4ff)
- **Transport Correction Only**
  - ![Transport Correction Only DL=10](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/db07f24a-2b4e-4e05-920d-33e58d9f552c)
- **Both Corrections**
  - ![Both Corrections DL=10](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/0fed00b2-7bff-4429-8ea7-9f6e8105df15)

#### **Simulations with DL = 30\*DH**
- **No Corrections**
  - ![No Corrections DL=30](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/3b1bdf3a-f095-440d-9db3-e3656c43efe0)
- **Linear Correction Only**
  - ![Linear Correction Only DL=30](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/24bd9d69-9a59-4667-b3b1-fb1f26cab11f)
- **Transport Correction Only**
  - ![Transport Correction Only DL=30](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/bf1c731b-9441-45a9-b55b-9bb30a0b6d1b)
- **Both Corrections**
  - ![Both Corrections DL=30](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/0f780af2-019b-4e06-963d-37a81c83eed9)

#### **Simulations with DL = 40\*DH**
- **No Corrections**
  - ![No Corrections DL=40](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/c9be6e3f-68b9-4f76-abb7-faf61dc21890)
- **Linear Correction Only**
  - ![Linear Correction Only DL=40](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/fa805f63-1c85-47a8-8928-b75fa534790c)
- **Transport Correction Only**
  - ![Transport Correction Only DL=40](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/e7038baa-cc9f-425f-88af-c99482b82954)
- **Both Corrections**
  - ![Both Corrections DL=40](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/0c660b27-60bf-4df5-9e42-c5a4b2db93a8)

### Summary with Straight Channel
- **Without Transport Correction**: Simulations are closer to analytical solutions but show particle clumping leading to crashes in simulations.
  - ![Clumping Issue](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/345743db-16c4-4510-95e3-f7219bdfd11b)
- **With Transport and Linear Corrections**: Results exhibit strong agreement with the analytical solution.

## FDA Geometry Simulations
Simulations in FDA geometries with `DL = 30*DH` and `DL = 40*DH` were conducted, focusing on the effectiveness of different correction strategies. Observer in this section is located at 0.5 L_in.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/fa3bc5b8-9cb8-4142-87b5-55137c9abc70)

### **DL = 30\*DH**
- **Linear Correction Only**
  - ![FDA Linear Correction Only DL=30](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/5f99353d-bca2-435e-902b-237890870542)
- **Both Corrections**
  - ![FDA Both Corrections DL=30](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/cefb82ed-888d-4faa-ae7a-b6c51c2bb673)

### **DL = 40\*DH**
- **Linear Correction Only**
  - ![FDA Linear Correction Only DL=40](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/ad441456-34ed-41a0-a006-d72ff48f30e0)
- **Both Corrections**
  - ![FDA Both Corrections DL=40](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/5a3756ef-600f-4258-a0af-04c2e3968d2b)
 
### Observations Without Transport Correction
Without using transport correction, the particle distribution is uneven in the sudden expansion region of the nozzle-type channel. This uneven distribution is particularly problematic in simulations of channels with sudden changes in geometry.

#### Visual Examples of Particle Clamping due to without Transport Correction
- **Resolution = DH/40**

- ![Particle Distribution Issue 1](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/a9bab099-98c0-4b0a-aacd-260eec1b1827)
- ![Particle Distribution Issue 2](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/d1a425c0-42ae-44b6-ad44-9940fefca240)

### Results with Transport and Linear Corrections
Using both transport and linear corrections, the results in the FDA simulations align well with predictions. The velocity profiles between the inlet and the shrinking region (DH) form an effective parabolic shape. However, the flow at sudden expansion region's flow is asymmetric. 

#### Visual of asymmetric flow at sudden expansion region
- **Resolution = DH/40**
  - ![FDA Simulation at DH/40](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/4dfd62b3-b326-4eb9-8108-5d4ab7c471b8)
  - ![Parabolic Profile Formation DH/40](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/9a46e54e-8531-403a-951f-6da8637b5076)

- **Resolution = DH/60**
  - ![Improved Particle Distribution DH/60](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/a9efd1ca-52e1-45bf-a000-55f25b47e12b)
  - ![Enhanced Parabolic Profile DH/60](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/9e8dd32a-31ef-4ce1-a4c7-bc5d6540795f)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/111049554/09ef0674-6619-43a4-87a3-18ce4dd812ea)

**Comment by Xiangyu-Hu** [comment]
@FengWang3119 Could you also have this issue. It may related to the transport formulation too.

**Comment by FengWang3119** [comment]
OK I will check it. 
Maybe measuring velocity from X = 0.9DL will make a difference

**Comment by YuVirtonomy** [comment]
@Xiangyu-Hu @FengWang3119 
With transport and linear corrections applied, the velocity profile fits analytically very well. In the FDA geometry, a parabolic flow forms between the inlet and the nozzle region. However, the flow becomes asymmetric after the sudden expansion in the FDA geometry.

**Comment by FengWang3119** [comment]
@YuVirtonomy  Did you add a constant time-reducing gravity to avoid the start-up instability?  Similar in the case, free stream flow around cynlinder.
I also meet this kind of problem for the long channel case.

**Comment by Xiangyu-Hu** [comment]
https://www.mdpi.com/2311-5521/6/1/4#B33-fluids-06-00004
you can see the instant flow is no symmetric even when Re  is much less that 500.

**Comment by Xiangyu-Hu** [comment]
> @Xiangyu-Hu @FengWang3119 With transport and linear corrections applied, the velocity profile fits analytically very well. In the FDA geometry, a parabolic flow forms between the inlet and the nozzle region. However, the flow becomes asymmetric after the sudden expansion in the FDA geometry.

https://www.mdpi.com/fluids/fluids-06-00004/article_deploy/html/images/fluids-06-00004-g003-550.jpg

**Comment by Xiangyu-Hu** [comment]
@YuVirtonomy and @FengWang3119 I suggest that we set user case both in 2d and 3d forms, so that Feng can later test turbulence model here.

**Comment by Xiangyu-Hu** [comment]
This seems not a code issue but due to low resolution.
