### ISSUE TITLE
hourglass control in soils

### ISSUE THREAD

**Issue by Shuaihao-Zhang** [Xiangyu-Hu/SPHinXsys#613]
Here, the snapshots of soil column collapse with and without hourglass control are shown:
For low resolution:
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/0109faa1-166b-4520-8c06-d2d6962c55c3)
For high resolution:
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/f20faf74-d86c-400a-b45e-98bf6536c8c9)
It can be seen that, at certain times, hourglass control appears to help in eliminating zigzag, but at other times the effect is not noticeable.

**Comment by Shuaihao-Zhang** [comment]
Additionally, there are also some other methods that can make the stress in soils very smooth.
(1) the moving least square (MLS) method
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/2bf73db3-8b5c-4c70-a801-f3b11a3c5765)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/f9a2c31c-210b-4c03-9f36-e285a3c1a9c9)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/9b7e1e4c-82a2-4a47-a932-56d82e7441ac)
Reference: 
[A new SPH-based approach to simulation of granular flows using viscous damping and stress regularisation.pdf](https://github.com/user-attachments/files/16115159/A.new.SPH-based.approach.to.simulation.of.granular.flows.using.viscous.damping.and.stress.regularisation.pdf)

(2) stress diffusion
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/436346ff-2b27-4d0b-aebe-21c65d5f4be7)
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/606dce9d-373a-4d25-881d-c2878a2cae54)
Reference:
[Large deformation analysis of granular ...pdf](https://github.com/user-attachments/files/16115174/Large.deformation.analysis.of.granular.pdf)

The stress diffusion method has been implemented in SPHinXsys.
Here is what I got after applying the stress diffusion, without the usage of hourglass control.
![image](https://github.com/Xiangyu-Hu/SPHinXsys/assets/43446342/a7ce43e6-aae7-4ee8-ac21-4718f9dcd69b)

**Comment by Xiangyu-Hu** [comment]
@Shuaihao-Zhang  I agree with your idea in Friday discussion now. The behaviors of the present model on soil need more detailed discussion.  From the figures, I am not able to identify which results are more reasonable. Certainly, the smoothing approach is always produces smoothed solution by definition. But our method, as discussed before, it is not a dissipative method.

**Comment by Xiangyu-Hu** [comment]
I guess the solution may related to the non shear part.

**Comment by Shuaihao-Zhang** [comment]
Thanks. We will check this problem in detail later.
