### ISSUE TITLE
Singular vriable never used for computing

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#638]
https://github.com/Xiangyu-Hu/SPHinXsys/blob/c1e062a1a9346f3ee256fd97832f590c462f9b44/tests/2d_examples/test_2d_diffusion_RobinBC/diffusion_RobinBC.h#L158C1-L158C40

It seems that the singular variable phi_infinity_ is never used for computing?

**Comment by ChenxiZhaoTUM** [comment]
`DiffusionRelaxation<Robin<ContactKernelGradientType>, DiffusionType>` in `diffusion_dynamics.hpp` 291-298 lines has used.

**Comment by Xiangyu-Hu** [comment]
Ok. Thanks.
