### ISSUE TITLE
How to apply the wetting effect?

### ISSUE THREAD

**Issue by Xiana-xu** [Xiangyu-Hu/SPHinXsys#645]
Hello, I have the following question:
1, Can the wetting effect in SPHinXsys be used in a fluid-solid coupling model between a fluid and an elastomer, or can it only be used in a simulation of fluid-solid interaction?
2, the wetting effect in the single-phase flow, the simulation results are accurate?
I will wetting effect in two-dimensional and three-dimensional droplet impact elastic beam case, no air particles, the contact angle was set to 30 and 160, respectively, the results of the two cases do not reflect the difference.

**Comment by Xiana-xu** [comment]
![Uploading 屏幕截图 2024-08-31 103709.png…]()

**Comment by Xiangyu-Hu** [comment]
Hello,

I think that the case you are looking at is quite complex. You can have a first explore as we have not handled such problem before. However, we would be happy to help through issue page. 
We also open for more formal collaboration.

Xiangyu
