### ISSUE TITLE
Seems a bug in test_2d_eulerian_supersonic_flow_new_BC

### ISSUE THREAD

**Issue by Xiangyu-Hu** [Xiangyu-Hu/SPHinXsys#650]
Test project C:/build
    Start 25: test_2d_eulerian_supersonic_flow_new_BC
1/1 Test #25: test_2d_eulerian_supersonic_flow_new_BC ...***Failed  247.04 sec
Particle relaxation was set to default (0).
Particle reload from input file was set to 1.
Generate regression test data was set to default (0).
State recording was set to 0.
Restart inactivated, i.e. restart_step (0).
N=0	Time = 0.003095238	dt = 0.003095238
N=500	Time = 1.426021891	dt = 0.0026687[12](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:13)
N=1000	Time = 2.787473310	dt = 0.002738317
N=1500	Time = 4.179992051	dt = 0.002821461
N=2000	Time = 5.594371866	dt = 0.002884705
N=2500	Time = 7.021402524	dt = 0.002904886
N=3000	Time = 8.481243027	dt = 0.002912009
N=3500	Time = 9.949600680	dt = 0.002946277
N=4000	Time = 11.305570902	dt = 0.002914381
N=4500	Time = 12.701695884	dt = 0.002951483
N=5000	Time = 14.182943269	dt = 0.002965377
N=5500	Time = 14.757984083	dt = 0.000583324
N=6000	Time = 14.977852726	dt = 0.001506186
N=6500	Time = 16.033056754	dt = 0.002840551
N=7000	Time = 17.405570922	dt = 0.002758674
N=7500	Time = 18.657846[13](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:14)8	dt = 0.002815529
N=8000	Time = 20.063502283	dt = 0.002797121
N=8500	Time = 21.471543551	dt = 0.002632537
N=9000	Time = 22.892970999	dt = 0.002766666
N=9500	Time = 24.281016416	dt = 0.002743484
N=10000	Time = 25.709847419	dt = 0.002883958
N=10500	Time = 27.[14](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:15)3265868	dt = 0.002975662
N=11000	Time = 28.119770189	dt = 0.001727697
N=1[15](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:16)00	Time = 28.795259872	dt = 0.000989920
N=12000	Time = 29.465842[16](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:17)1	dt = 0.001940631
N=12500	Time = 30.315705353	dt = 0.001829291
N=13000	Time = 31.366627826	dt = 0.002304918
N=13500	Time = 32.033029155	dt = 0.001323722
N=14000	Time = 32.748799287	dt = 0.0015518[17](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:18)
N=14500	Time = 33.276035170	dt = 0.002634898
N=15000	Time = 34.113414821	dt = 0.0020403[18](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:19)
N=15500	Time = 35.173542284	dt = 0.001210626
N=16000	Time = 36.079390856	dt = 0.001161615
N=16500	Time = 36.950305276	dt = 0.001572580
N=17000	Time = 37.594424506	dt = 0.001451106
N=17500	Time = 38.345759972	dt = 0.001394039
N=18000	Time = 39.223442823	dt = 0.001516370
Total wall time for computation: 246.949553100 seconds.
MaximumSpeed[0] in Snapshot_500 is beyond the exception, and difference is 153.253523574
MaximumSpeed[0] in Snapshot_1000 is beyond the exception, and difference is [19](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:20)31952551.898786783
MaximumSpeed[0] in Snapshot_1500 is beyond the exception, and difference is 1938725614.755589962
MaximumSpeed[0] in Snapshot_[20](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:21)00 is beyond the exception, and difference is 1945494983.009193897
MaximumSpeed[0] in Snapshot_2500 is beyond the exception, and difference is 1945984443.356199026
MaximumSpeed[0] in Snapshot_3000 is beyond the exception, and difference is 1943943415.744412661
MaximumSpeed[0] in Snapshot_3500 is beyond the exception, and difference is 1941319130.624794006
MaximumSpeed[0] in Snapshot_4000 is beyond the exception, and difference is 1939071393.784265280
MaximumSpeed[0] in Snapshot_4500 is beyond the exception, and difference is 1947290793.873203516
MaximumSpeed[0] in Snapshot_5000 is beyond the exception, and difference is 1947922931.70[21](https://github.com/Xiangyu-Hu/SPHinXsys/actions/runs/10706811923/job/29715631318#step:11:22)03853
MaximumSpeed[0] in Snapshot_5500 is beyond the exception, and difference is inf
MaximumSpeed[0] in Snapshot_6000 is beyond the exception, and difference is inf
MaximumSpeed[0] in Snapshot_6500 is beyond the exception, and difference is inf
MaximumSpeed[0] in Snapshot_7000 is beyond the exception, and difference is inf
MaximumSpeed[0] in Snapshot_7500 is beyond the exception, and difference is inf

It seems that some time the code go wrong.

**Comment by Xiangyu-Hu** [comment]
Is the bug found?

**Comment by ZhentongWang** [comment]
> Is the bug found?

I checked the numerical results, and the results are fine. 
The problem seems happening in the regression file. I have created the pull request where I use a different regression strategy to create the regression file.

**Comment by ZhentongWang** [comment]
> Is the bug found?

![image](https://github.com/user-attachments/assets/3fe92e64-6bf9-4178-a07c-d10dd0ac2289)
some time, its other's case failed in the Linux-test, and I will re-run this again.

**Comment by Xiangyu-Hu** [comment]
> > Is the bug found?
> 
> ![image](https://private-user-images.githubusercontent.com/126269817/365631674-3fe92e64-6bf9-4178-a07c-d10dd0ac2289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODQzMTcsIm5iZiI6MTcyNTg4NDAxNywicGF0aCI6Ii8xMjYyNjk4MTcvMzY1NjMxNjc0LTNmZTkyZTY0LTZiZjktNDE3OC1hMDdjLWQxMGRkMGFjMjI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMjEzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDJkZmQ1OTEyMjM3N2ZiNGZhMTIxNWY1Y2EwYTcwMmM2NzFkYTYxYTU2ODYzNzY1ZTM4OTA2ZTk2ZTc1OGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DlwljjVq6CdBHx9Dr4-ZIUvmLP4FH9CJs4rgJEsje4M) some time, its other's case failed in the Linux-test, and I will re-run this again.

Yes. But the optimization case is not certain by itself. But the Eulerian case should be certain.

**Comment by ZhentongWang** [comment]
> > > Is the bug found?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/126269817/365631674-3fe92e64-6bf9-4178-a07c-d10dd0ac2289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODQzMTcsIm5iZiI6MTcyNTg4NDAxNywicGF0aCI6Ii8xMjYyNjk4MTcvMzY1NjMxNjc0LTNmZTkyZTY0LTZiZjktNDE3OC1hMDdjLWQxMGRkMGFjMjI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMjEzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDJkZmQ1OTEyMjM3N2ZiNGZhMTIxNWY1Y2EwYTcwMmM2NzFkYTYxYTU2ODYzNzY1ZTM4OTA2ZTk2ZTc1OGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DlwljjVq6CdBHx9Dr4-ZIUvmLP4FH9CJs4rgJEsje4M) some time, its other's case failed in the Linux-test, and I will re-run this again.
> 
> Yes. But the optimization case is not certain by itself. But the Eulerian case should be certain.

Currently, the Eulerian supersonic flow case can pass.

**Comment by Xiangyu-Hu** [comment]
So no big is found?

**Comment by Xiangyu-Hu** [comment]
How can we explain the issue list above?

**Comment by ZhentongWang** [comment]
> So no big is found?

I have tried many times to simulate this case, and the results (including velocity contour) seem correct and convincing. 
Therefore, I don't think there is a bug in the simulation.

**Comment by ZhentongWang** [comment]
> How can we explain the issue list above?

In Linux: I have tried many time and the output is stable as follows:
![AXBE2$9}`KP EOOYVGG@3QV](https://github.com/user-attachments/assets/38adb409-4bda-4904-b257-c6d5c57ba9c4)



In Window: also tried many times and the output is as follows:
![2222](https://github.com/user-attachments/assets/00e92563-f61c-45de-856e-b09ed00d3aee)





I have noticed that the output that you uploaded shows there was many dt very small, but I haven't met this phenomenon during the many simulations I have done.

**Comment by Xiangyu-Hu** [comment]
@ZhentongWang may be the problem is related to particle generation. For you many simulation did you re generate particle every time?

**Comment by ZhentongWang** [comment]
> @ZhentongWang may be the problem is related to particle generation. For you many simulation did you re generate particle every time?

Yes, I use particle relaxation every time.
Here, some results in Linux show as follows:
![L2](https://github.com/user-attachments/assets/39b59203-cf68-4cb5-a311-918cb232bf0c)
![L3](https://github.com/user-attachments/assets/78397b4b-a00a-4bc6-b986-b823d69186de)
![L4](https://github.com/user-attachments/assets/e800ea10-8603-42b9-8e71-438ab9b8b2fa)


Here, some results in Windows show as follows:
![W2](https://github.com/user-attachments/assets/092cb07c-4bf6-4ac8-ac96-d5635814fa2f)
![W3](https://github.com/user-attachments/assets/28a96043-bb77-42ab-ae87-0a2939337250)
![W4](https://github.com/user-attachments/assets/627d176f-4152-4f87-9908-6dd9b3545d9d)


The dt in these results also seems stable.
