### ISSUE TITLE
SPH-ENOG implementation

### ISSUE THREAD

**Issue by GUT2060** [Xiangyu-Hu/SPHinXsys#653]
Dear SPHinXsys community,

In the [Essentially non-hourglass SPH elastic dynamics](https://www.sciencedirect.com/science/article/pii/S0021999124003218?via%3Dihub) paper, it is mentioned that the code for the study is to be found in the SPHinXsys repository.
while the paper can be found under the publications section in the readme of the ul_plastic_hourglass_try branch, the link to the paper is erronuous as it leads to 
[A dynamic relaxation method with operator splitting and random-choice strategy for SPH](https://www.sciencedirect.com/science/article/abs/pii/S002199912200167X?via%3Dihub)

i also cannot find a clear path to see the implementation of the Essentially non-hourglass SPH elastic dynamics paper in the code , is there a specific branch i need to check ? 
Thanks

**Comment by Xiangyu-Hu** [comment]
The code in master branch already.
