### ISSUE TITLE
CMake preset is not convenient

### ISSUE THREAD

**Issue by WeiyiVirtonomy** [Xiangyu-Hu/SPHinXsys#654]
In `CMakePresets.json`, the path to the toolchain file is set to

`"CMAKE_TOOLCHAIN_FILE": "'$/home/xyhu/vcpkg/scripts/buildsystems/vcpkg.cmake'"`

I have to change it to the path of vcpkg on my machine. Could you use a more general path like `"${env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"` to make it more convenient?

**Comment by Xiangyu-Hu** [comment]
Yes. The preset is will be in ignorance list after the next pull request.
