### ISSUE TITLE
RelaxationStepLevelSetCorrectionInner doesn't work for 3d multi-resolution

### ISSUE THREAD

**Issue by WeiyiVirtonomy** [Xiangyu-Hu/SPHinXsys#663]
The relaxation using `RelaxationStepLevelSetCorrectionInner` produces weird particle distribution

Lattice:
![Screenshot 2024-09-20 130113](https://github.com/user-attachments/assets/5dbf23bf-9059-4ea4-9970-77f3af8db5d3)

After relaxation:
![Screenshot 2024-09-20 130120](https://github.com/user-attachments/assets/86325e72-4d9b-4419-862e-019d662b58ea)

Gaps:
![Screenshot 2024-09-20 130126](https://github.com/user-attachments/assets/a8697ea0-660a-454b-b49a-3c98321ea5d6)

`RelaxationStepInner` doesn't have this problem:
<img width="401" alt="image" src="https://github.com/user-attachments/assets/467b98bc-e382-4a94-bdba-483eaedb771b">

There might be a bug in the 3d level-set shape of this beam

**Comment by Xiangyu-Hu** [comment]
@WeiyiVirtonomy yes. It seems like.
@Nafug22 could you have check on the implementation? Thanks.

**Comment by Xiangyu-Hu** [comment]
@WeiyiVirtonomy Could you make small test case for multi-resolution relaxation? Thanks,

**Comment by WeiyiVirtonomy** [comment]
> @WeiyiVirtonomy Could you make small test case for multi-resolution relaxation? Thanks,

Sure. Would you like me to use this beam in the test, or would you prefer more complicated shapes? 

We have a 3d teapot with surface refinement, and I wonder why that one works well. Could the problem lie in the shape generated by simtk?

**Comment by Xiangyu-Hu** [comment]
@WeiyiVirtonomy Just use this simple case.

**Comment by WeiyiVirtonomy** [comment]
The problem is now solved after fixing dW(h_ratio) of 3D and defining the level set refinement level correctly
