### ISSUE TITLE
Momentum conservative issue

### ISSUE THREAD

**Issue by Shuaihao-Zhang** [Xiangyu-Hu/SPHinXsys#664]
I found the reason why the momentum is not conservative.
First, we can make sure that particle neighbors are symmetric after my tests. If particle i is a neighbor of particle j, then particle j is also a neighbor of particle i.
The momentum issue is because I used `rho_[index_i]  * Vol_[index_i] * vel_[index_i]` to calculate the momentum.
If I use `mass_[index_i]  * vel_[index_i]`, then the momentum is exactly conservative.
So, the real problem is `rho_[index_i]  * Vol_[index_i] != mass_[index_i]`.

**Comment by Xiangyu-Hu** [comment]
This should hold at the beginning of each advection step.
