### ISSUE TITLE
There was an issue while simulating the test_2d_free_steam1-around_cylinder case？

### ISSUE THREAD

**Issue by duanlinlim** [Xiangyu-Hu/SPHinXsys#693]
Error message shows that the program cannot find a file named Cylinder_rld.xml when attempting to load it, causing the program to fail to continue running and exit abnormally

Error in load file: Error=XML_ERROR_FILE_NOT_FOUND ErrorID=3 (0x3) Line number=0: filename=./reload/Cylinder_rld.xml

**Comment by Xiangyu-Hu** [comment]
The code should be run with command options either to generate particles and write them on disk or run the test case with generated particles by read the data. You are try to run the case without the particles file ready.
