### ISSUE TITLE
How to generate particle files？

### ISSUE THREAD

**Issue by duanlinlim** [Xiangyu-Hu/SPHinXsys#695]
Error in load file: Error=XML_ERROR_FILE_NOT_FOUND ErrorID=3 (0x3) Line number=0: filename=./reload/Shell_rld.xml

**Comment by duanlinlim** [comment]
Does the case of test_2d_shell-beam-collision and test_2d_ball_sthell-collision represent the cases of adding elastic beams and small balls entering the water during dam failure, respectively

**Comment by Xiangyu-Hu** [comment]
You can check the source and find it out by running the case. To generate particles, you check the usage of the command option from the CMakeList file for the case.
