### ISSUE TITLE
How to generate particle files without importing the model?

### ISSUE THREAD

**Issue by duanlinlim** [Xiangyu-Hu/SPHinXsys#702]
Simulated inflow and outflow cases appear
Error in load file: Error=XML_ERROR_FILE_NOT_FOUND ErrorID=3 (0x3) Line number=0: filename=./reload/Cylinder_rld.xml

E:\sphinxsys-build-2022\tests\2d_examples\test_2d_water_entry_exit\bin\Release\test_2d_water_entry_exit.exe (进程 18996)已退出，代码为 1。
I watched a video on Bilibili about generating multi-resolution isotropic particle distributions from complex geometric shapes. This video requires importing a model, but it seems that this inflow and outflow case does not require importing a model.
How should the above problems be solved?

**Comment by duanlinlim** [comment]
Error in load file: Error=XML_ERROR_FILE_NOT_FOUND ErrorID=3 (0x3) Line number=0: filename=./reload/Cylinder_rld.xml

E:\sphinxsys-build-2022\tests\2d_examples\test_2d_water_entry_exit\bin\Release\test_2d_water_entry_exit.exe (进程 18996)
This kind of problem is to find a Cylinder.dat file use test_2d_particle_generator_single_resolution Generate Cylinder_rld.xml？

**Comment by Xiangyu-Hu** [comment]
The 2d water exit case does not require an input and can run properly, I have not catch your question yet.
