### ISSUE TITLE
How to test_2d_  measure water_entry_exit  velocity?

### ISSUE THREAD

**Issue by duanlinlim** [Xiangyu-Hu/SPHinXsys#707]
I encountered an issue with adding speed measurement in the case
Error: the variable 'velocity' is not registered!
E:\SPHinXsys\SPHinXsys-master\src\shared\particles\base_particles.hpp:136
_**In this case, do we need to regenerate Cylinder_rld.xml every time we make modifications, and then simulate the case**_

**Comment by Xiangyu-Hu** [comment]
It suggest the variable 'velocity' you want to use is not registered. I guess you need to use "Velocity" with capital "V".
