### ISSUE TITLE
粒子无关性问题

### ISSUE THREAD

**Issue by bithuangcan** [Xiangyu-Hu/SPHinXsys#79]
老师，您好！我在用SPH模拟岩土力学问题时，遇到了粒子无关性检验不收敛的问题。
例如，二维溃坝问题表现为粒子越多，最终滑动距离越远。
岩土力学采用的是弹塑性本构，屈服准则用D-P准则下的非关联塑性流动法则。壁面条件采用的是通过核函数插值得到其密度、应力、速度（反向）。

**Comment by Xiangyu-Hu** [comment]
Are you using SPHinXsys or other code for your problem?
Basically, the issues posted here should be with SPHinXsys.

**Comment by bithuangcan** [comment]
Thank you. Professor Hu. In fact, I use the DualSPHysics code and implement into soil model with its framework. I'm sorry to ask a question that has nothing to do with SPHinXsys.

**Comment by Xiangyu-Hu** [comment]
No a problem. SPHinXsys is open for implementing soil models too. You are welcomed for  implement it and I am happy to discuss if we have numerical examples on it.
