### ISSUE TITLE
Availability of one-layer (shell) elastic solid 

### ISSUE THREAD

**Issue by rubensamarojr** [Xiangyu-Hu/SPHinXsys#97]
I would like to know if the one-layer elastic solid, e.g., https://www.youtube.com/watch?v=VpzV8dhn2Vs, is already available in the SPHinXsys github repository.
Thanks

**Comment by Xiangyu-Hu** [comment]
Thanks for your interest. The function is a nearest work and still in the internal developing branch. However, I can assure you that it will be publish in Github repository as soon as possible. 
Xiangyu

**Comment by rubensamarojr** [comment]
Dear Prof. Xiangyu, thank you for your prompt reply. I'm waiting for the updates.
Best,
Rubens
